_format_version: "3.0"
services:
- connect_timeout: 60000
  host: $(ServiceName).$(oc_project).svc.cluster.local
  name: $(ServiceName)-$(ambient_prefix)
  path: /$(app_context_path)
  port: $(ServicePort)
  protocol: http
  read_timeout: 60000
  retries: 8
  write_timeout: 60000
  routes:
  - name: $(ServiceName)-$(ambient_prefix)
    paths:
    - /$(app_context_path)
    preserve_host: false
    protocols:
      - http
    regex_priority: 0
    strip_path: true