//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaServices.ConsultaCupoRotativo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.serfinansa.ws.asnetla.com/", ConfigurationName="ConsultaCupoRotativo.CreditCardTRXI")]
    public interface CreditCardTRXI {
        
        // CODEGEN: Generating message contract since the operation executeProcessing is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BancaServices.ConsultaCupoRotativo.executeProcessingResponse executeProcessing(BancaServices.ConsultaCupoRotativo.executeProcessingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.ConsultaCupoRotativo.executeProcessingResponse> executeProcessingAsync(BancaServices.ConsultaCupoRotativo.executeProcessingRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.serfinansa.ws.asnetla.com/")]
    public partial class creditCardTRXRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private creditCardTRXRequestProcessingDTO creditCardTRXRequestProcessingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public creditCardTRXRequestProcessingDTO creditCardTRXRequestProcessing {
            get {
                return this.creditCardTRXRequestProcessingField;
            }
            set {
                this.creditCardTRXRequestProcessingField = value;
                this.RaisePropertyChanged("creditCardTRXRequestProcessing");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.serfinansa.ws.asnetla.com/")]
    public partial class creditCardTRXRequestProcessingDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usrIdField;
        
        private string usrPswField;
        
        private string codigoCanalField;
        
        private string codigoEntidadField;
        
        private string codigoAplicacionField;
        
        private string codigoTransaccionField;
        
        private string codigoTerminalField;
        
        private string codigoEstablecimientoField;
        
        private string fechaTransaccionField;
        
        private string horaTransaccionField;
        
        private string fechaEfectivaTransaccionField;
        
        private string codigoSwitchField;
        
        private string dispositivoField;
        
        private string numeroAuditoriaField;
        
        private string consecutivoField;
        
        private string tipoTransaccionField;
        
        private string nomUbicPOSAdquField;
        
        private string tRACKIIField;
        
        private string numeroTarjetaField;
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string productoField;
        
        private string subtipoField;
        
        private string valorTransaccionField;
        
        private string numeroCuotasField;
        
        private string fillerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string usrId {
            get {
                return this.usrIdField;
            }
            set {
                this.usrIdField = value;
                this.RaisePropertyChanged("usrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string usrPsw {
            get {
                return this.usrPswField;
            }
            set {
                this.usrPswField = value;
                this.RaisePropertyChanged("usrPsw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoCanal {
            get {
                return this.codigoCanalField;
            }
            set {
                this.codigoCanalField = value;
                this.RaisePropertyChanged("codigoCanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoEntidad {
            get {
                return this.codigoEntidadField;
            }
            set {
                this.codigoEntidadField = value;
                this.RaisePropertyChanged("codigoEntidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string codigoAplicacion {
            get {
                return this.codigoAplicacionField;
            }
            set {
                this.codigoAplicacionField = value;
                this.RaisePropertyChanged("codigoAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoTransaccion {
            get {
                return this.codigoTransaccionField;
            }
            set {
                this.codigoTransaccionField = value;
                this.RaisePropertyChanged("codigoTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string codigoTerminal {
            get {
                return this.codigoTerminalField;
            }
            set {
                this.codigoTerminalField = value;
                this.RaisePropertyChanged("codigoTerminal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string codigoEstablecimiento {
            get {
                return this.codigoEstablecimientoField;
            }
            set {
                this.codigoEstablecimientoField = value;
                this.RaisePropertyChanged("codigoEstablecimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string fechaTransaccion {
            get {
                return this.fechaTransaccionField;
            }
            set {
                this.fechaTransaccionField = value;
                this.RaisePropertyChanged("fechaTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string horaTransaccion {
            get {
                return this.horaTransaccionField;
            }
            set {
                this.horaTransaccionField = value;
                this.RaisePropertyChanged("horaTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string fechaEfectivaTransaccion {
            get {
                return this.fechaEfectivaTransaccionField;
            }
            set {
                this.fechaEfectivaTransaccionField = value;
                this.RaisePropertyChanged("fechaEfectivaTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string codigoSwitch {
            get {
                return this.codigoSwitchField;
            }
            set {
                this.codigoSwitchField = value;
                this.RaisePropertyChanged("codigoSwitch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string dispositivo {
            get {
                return this.dispositivoField;
            }
            set {
                this.dispositivoField = value;
                this.RaisePropertyChanged("dispositivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string numeroAuditoria {
            get {
                return this.numeroAuditoriaField;
            }
            set {
                this.numeroAuditoriaField = value;
                this.RaisePropertyChanged("numeroAuditoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
                this.RaisePropertyChanged("consecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string tipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
                this.RaisePropertyChanged("tipoTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string nomUbicPOSAdqu {
            get {
                return this.nomUbicPOSAdquField;
            }
            set {
                this.nomUbicPOSAdquField = value;
                this.RaisePropertyChanged("nomUbicPOSAdqu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string TRACKII {
            get {
                return this.tRACKIIField;
            }
            set {
                this.tRACKIIField = value;
                this.RaisePropertyChanged("TRACKII");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
                this.RaisePropertyChanged("numeroTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string subtipo {
            get {
                return this.subtipoField;
            }
            set {
                this.subtipoField = value;
                this.RaisePropertyChanged("subtipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string valorTransaccion {
            get {
                return this.valorTransaccionField;
            }
            set {
                this.valorTransaccionField = value;
                this.RaisePropertyChanged("valorTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string numeroCuotas {
            get {
                return this.numeroCuotasField;
            }
            set {
                this.numeroCuotasField = value;
                this.RaisePropertyChanged("numeroCuotas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string filler {
            get {
                return this.fillerField;
            }
            set {
                this.fillerField = value;
                this.RaisePropertyChanged("filler");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.serfinansa.ws.asnetla.com/")]
    public partial class tarjetasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroTarjetaField;
        
        private string estadoTarjetaField;
        
        private string saldoDisponibleField;
        
        private string cupoTotalField;
        
        private string subtipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
                this.RaisePropertyChanged("numeroTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estadoTarjeta {
            get {
                return this.estadoTarjetaField;
            }
            set {
                this.estadoTarjetaField = value;
                this.RaisePropertyChanged("estadoTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string saldoDisponible {
            get {
                return this.saldoDisponibleField;
            }
            set {
                this.saldoDisponibleField = value;
                this.RaisePropertyChanged("saldoDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cupoTotal {
            get {
                return this.cupoTotalField;
            }
            set {
                this.cupoTotalField = value;
                this.RaisePropertyChanged("cupoTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string subtipo {
            get {
                return this.subtipoField;
            }
            set {
                this.subtipoField = value;
                this.RaisePropertyChanged("subtipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.serfinansa.ws.asnetla.com/")]
    public partial class creditCardTRXResponseProcessingDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroAutorizacionField;
        
        private string codigoRespuestaField;
        
        private string descripcionField;
        
        private string nombreTarjetaHabienteField;
        
        private string numeroTarjetasField;
        
        private string tipoIdentificacionField;
        
        private string numeroIdentificacionField;
        
        private string numeroCuentaField;
        
        private string estadoCuentaField;
        
        private string saldoDisponibleField;
        
        private string subtipoField;
        
        private string fillerField;
        
        private tarjetasDTO[] infoTarjetasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                this.numeroAutorizacionField = value;
                this.RaisePropertyChanged("numeroAutorizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreTarjetaHabiente {
            get {
                return this.nombreTarjetaHabienteField;
            }
            set {
                this.nombreTarjetaHabienteField = value;
                this.RaisePropertyChanged("nombreTarjetaHabiente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroTarjetas {
            get {
                return this.numeroTarjetasField;
            }
            set {
                this.numeroTarjetasField = value;
                this.RaisePropertyChanged("numeroTarjetas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
                this.RaisePropertyChanged("tipoIdentificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                this.numeroIdentificacionField = value;
                this.RaisePropertyChanged("numeroIdentificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
                this.RaisePropertyChanged("numeroCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string estadoCuenta {
            get {
                return this.estadoCuentaField;
            }
            set {
                this.estadoCuentaField = value;
                this.RaisePropertyChanged("estadoCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string saldoDisponible {
            get {
                return this.saldoDisponibleField;
            }
            set {
                this.saldoDisponibleField = value;
                this.RaisePropertyChanged("saldoDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string subtipo {
            get {
                return this.subtipoField;
            }
            set {
                this.subtipoField = value;
                this.RaisePropertyChanged("subtipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string filler {
            get {
                return this.fillerField;
            }
            set {
                this.fillerField = value;
                this.RaisePropertyChanged("filler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infoTarjetas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public tarjetasDTO[] infoTarjetas {
            get {
                return this.infoTarjetasField;
            }
            set {
                this.infoTarjetasField = value;
                this.RaisePropertyChanged("infoTarjetas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.serfinansa.ws.asnetla.com/")]
    public partial class creditCardTRXResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private creditCardTRXResponseProcessingDTO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public creditCardTRXResponseProcessingDTO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeProcessingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.serfinansa.ws.asnetla.com/", Order=0)]
        public BancaServices.ConsultaCupoRotativo.creditCardTRXRequest creditCardTRXRequest;
        
        public executeProcessingRequest() {
        }
        
        public executeProcessingRequest(BancaServices.ConsultaCupoRotativo.creditCardTRXRequest creditCardTRXRequest) {
            this.creditCardTRXRequest = creditCardTRXRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class executeProcessingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.serfinansa.ws.asnetla.com/", Order=0)]
        public BancaServices.ConsultaCupoRotativo.creditCardTRXResponse creditCardTRXResponse;
        
        public executeProcessingResponse() {
        }
        
        public executeProcessingResponse(BancaServices.ConsultaCupoRotativo.creditCardTRXResponse creditCardTRXResponse) {
            this.creditCardTRXResponse = creditCardTRXResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreditCardTRXIChannel : BancaServices.ConsultaCupoRotativo.CreditCardTRXI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditCardTRXIClient : System.ServiceModel.ClientBase<BancaServices.ConsultaCupoRotativo.CreditCardTRXI>, BancaServices.ConsultaCupoRotativo.CreditCardTRXI {
        
        public CreditCardTRXIClient() {
        }
        
        public CreditCardTRXIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditCardTRXIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardTRXIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardTRXIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.ConsultaCupoRotativo.executeProcessingResponse BancaServices.ConsultaCupoRotativo.CreditCardTRXI.executeProcessing(BancaServices.ConsultaCupoRotativo.executeProcessingRequest request) {
            return base.Channel.executeProcessing(request);
        }
        
        public BancaServices.ConsultaCupoRotativo.creditCardTRXResponse executeProcessing(BancaServices.ConsultaCupoRotativo.creditCardTRXRequest creditCardTRXRequest) {
            BancaServices.ConsultaCupoRotativo.executeProcessingRequest inValue = new BancaServices.ConsultaCupoRotativo.executeProcessingRequest();
            inValue.creditCardTRXRequest = creditCardTRXRequest;
            BancaServices.ConsultaCupoRotativo.executeProcessingResponse retVal = ((BancaServices.ConsultaCupoRotativo.CreditCardTRXI)(this)).executeProcessing(inValue);
            return retVal.creditCardTRXResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.ConsultaCupoRotativo.executeProcessingResponse> BancaServices.ConsultaCupoRotativo.CreditCardTRXI.executeProcessingAsync(BancaServices.ConsultaCupoRotativo.executeProcessingRequest request) {
            return base.Channel.executeProcessingAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.ConsultaCupoRotativo.executeProcessingResponse> executeProcessingAsync(BancaServices.ConsultaCupoRotativo.creditCardTRXRequest creditCardTRXRequest) {
            BancaServices.ConsultaCupoRotativo.executeProcessingRequest inValue = new BancaServices.ConsultaCupoRotativo.executeProcessingRequest();
            inValue.creditCardTRXRequest = creditCardTRXRequest;
            return ((BancaServices.ConsultaCupoRotativo.CreditCardTRXI)(this)).executeProcessingAsync(inValue);
        }
    }
}
