//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaServices.ConsultaTarjetaSR {
    using System.Runtime.Serialization;
    
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaTarjetas_req", Namespace="http://schema.rbm.com")]
    [System.SerializableAttribute()]
    public partial class ConsultaTarjetas_req : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codigoCanalField;
        
        private string codigoEntidadField;
        
        private string numeroDocumentoField;
        
        private string tipoDocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoCanal {
            get {
                return this.codigoCanalField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCanalField, value) != true)) {
                    this.codigoCanalField = value;
                    this.RaisePropertyChanged("codigoCanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoEntidad {
            get {
                return this.codigoEntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoEntidadField, value) != true)) {
                    this.codigoEntidadField = value;
                    this.RaisePropertyChanged("codigoEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroDocumentoField, value) != true)) {
                    this.numeroDocumentoField = value;
                    this.RaisePropertyChanged("numeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoDocumentoField, value) != true)) {
                    this.tipoDocumentoField = value;
                    this.RaisePropertyChanged("tipoDocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaTarjetas_resp", Namespace="http://schema.rbm.com")]
    [System.SerializableAttribute()]
    public partial class ConsultaTarjetas_resp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private BancaServices.ConsultaTarjetaSR.ArrayOf_tns1_ConsultaTarjetas_dto arrayConsultaTarjetasField;
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public BancaServices.ConsultaTarjetaSR.ArrayOf_tns1_ConsultaTarjetas_dto arrayConsultaTarjetas {
            get {
                return this.arrayConsultaTarjetasField;
            }
            set {
                if ((object.ReferenceEquals(this.arrayConsultaTarjetasField, value) != true)) {
                    this.arrayConsultaTarjetasField = value;
                    this.RaisePropertyChanged("arrayConsultaTarjetas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoRespuestaField, value) != true)) {
                    this.codigoRespuestaField = value;
                    this.RaisePropertyChanged("codigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionRespuestaField, value) != true)) {
                    this.descripcionRespuestaField = value;
                    this.RaisePropertyChanged("descripcionRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOf_tns1_ConsultaTarjetas_dto", Namespace="http://wsdl.rbm.com", ItemName="item")]
    [System.SerializableAttribute()]
    public class ArrayOf_tns1_ConsultaTarjetas_dto : System.Collections.Generic.List<BancaServices.ConsultaTarjetaSR.ConsultaTarjetas_dto> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaTarjetas_dto", Namespace="http://schema.rbm.com")]
    [System.SerializableAttribute()]
    public partial class ConsultaTarjetas_dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string estadoTarjetaField;
        
        private string numeroTarjetaField;
        
        private string numeroTarjetaCompletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string estadoTarjeta {
            get {
                return this.estadoTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoTarjetaField, value) != true)) {
                    this.estadoTarjetaField = value;
                    this.RaisePropertyChanged("estadoTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroTarjetaField, value) != true)) {
                    this.numeroTarjetaField = value;
                    this.RaisePropertyChanged("numeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroTarjetaCompleto {
            get {
                return this.numeroTarjetaCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroTarjetaCompletoField, value) != true)) {
                    this.numeroTarjetaCompletoField = value;
                    this.RaisePropertyChanged("numeroTarjetaCompleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsdl.rbm.com", ConfigurationName="ConsultaTarjetaSR.ConsultaTarjetas")]
    public interface ConsultaTarjetas {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usrId del espacio de nombres http://wsdl.rbm.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoResponse getTarjetasDocumento(BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoResponse> getTarjetasDocumentoAsync(BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTarjetasDocumentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTarjetasDocumento", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequestBody Body;
        
        public getTarjetasDocumentoRequest() {
        }
        
        public getTarjetasDocumentoRequest(BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class getTarjetasDocumentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usrId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usrPsw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BancaServices.ConsultaTarjetaSR.ConsultaTarjetas_req request;
        
        public getTarjetasDocumentoRequestBody() {
        }
        
        public getTarjetasDocumentoRequestBody(string usrId, string usrPsw, BancaServices.ConsultaTarjetaSR.ConsultaTarjetas_req request) {
            this.usrId = usrId;
            this.usrPsw = usrPsw;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTarjetasDocumentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTarjetasDocumentoResponse", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoResponseBody Body;
        
        public getTarjetasDocumentoResponse() {
        }
        
        public getTarjetasDocumentoResponse(BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class getTarjetasDocumentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.ConsultaTarjetaSR.ConsultaTarjetas_resp getTarjetasDocumentoReturn;
        
        public getTarjetasDocumentoResponseBody() {
        }
        
        public getTarjetasDocumentoResponseBody(BancaServices.ConsultaTarjetaSR.ConsultaTarjetas_resp getTarjetasDocumentoReturn) {
            this.getTarjetasDocumentoReturn = getTarjetasDocumentoReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaTarjetasChannel : BancaServices.ConsultaTarjetaSR.ConsultaTarjetas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaTarjetasClient : System.ServiceModel.ClientBase<BancaServices.ConsultaTarjetaSR.ConsultaTarjetas>, BancaServices.ConsultaTarjetaSR.ConsultaTarjetas {
        
        public ConsultaTarjetasClient() {
        }
        
        public ConsultaTarjetasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaTarjetasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaTarjetasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaTarjetasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoResponse BancaServices.ConsultaTarjetaSR.ConsultaTarjetas.getTarjetasDocumento(BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequest request) {
            return base.Channel.getTarjetasDocumento(request);
        }
        
        public BancaServices.ConsultaTarjetaSR.ConsultaTarjetas_resp getTarjetasDocumento(string usrId, string usrPsw, BancaServices.ConsultaTarjetaSR.ConsultaTarjetas_req request) {
            BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequest inValue = new BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequest();
            inValue.Body = new BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.request = request;
            BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoResponse retVal = ((BancaServices.ConsultaTarjetaSR.ConsultaTarjetas)(this)).getTarjetasDocumento(inValue);
            return retVal.Body.getTarjetasDocumentoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoResponse> BancaServices.ConsultaTarjetaSR.ConsultaTarjetas.getTarjetasDocumentoAsync(BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequest request) {
            return base.Channel.getTarjetasDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoResponse> getTarjetasDocumentoAsync(string usrId, string usrPsw, BancaServices.ConsultaTarjetaSR.ConsultaTarjetas_req request) {
            BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequest inValue = new BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequest();
            inValue.Body = new BancaServices.ConsultaTarjetaSR.getTarjetasDocumentoRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.request = request;
            return ((BancaServices.ConsultaTarjetaSR.ConsultaTarjetas)(this)).getTarjetasDocumentoAsync(inValue);
        }
    }
}
