//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaServices.AsNetSeguridadCVV2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://transacciones.services.ws.asnetla.com/", ConfigurationName="AsNetSeguridadCVV2.TransaccionesProxy")]
    public interface TransaccionesProxy {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación AplicarTransaccion no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BancaServices.AsNetSeguridadCVV2.AplicarTransaccionResponse1 AplicarTransaccion(BancaServices.AsNetSeguridadCVV2.AplicarTransaccionRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.AsNetSeguridadCVV2.AplicarTransaccionResponse1> AplicarTransaccionAsync(BancaServices.AsNetSeguridadCVV2.AplicarTransaccionRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.transacciones.services.ws.asnetla.com/")]
    public partial class aplicarTransaccionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransaccionAPPDTO aplicarTransaccionRequest1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aplicarTransaccionRequest", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TransaccionAPPDTO aplicarTransaccionRequest1 {
            get {
                return this.aplicarTransaccionRequest1Field;
            }
            set {
                this.aplicarTransaccionRequest1Field = value;
                this.RaisePropertyChanged("aplicarTransaccionRequest1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransaccionAPPResponseDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.transacciones.services.ws.asnetla.com/")]
    public partial class TransaccionAPPDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoAplicacionField;
        
        private string codigoProcesamientoField;
        
        private string fechaTransaccionField;
        
        private string horaTransaccionField;
        
        private string fechaEfectivaField;
        
        private string codigoCanalField;
        
        private string codigoSwitchField;
        
        private string codigoDispositivoField;
        
        private string consecutivoField;
        
        private string tipoTransaccionField;
        
        private string codigoEntidadField;
        
        private string userIdField;
        
        private string passwordIdField;
        
        private string numeroTarjetaField;
        
        private string numeroDocumentoField;
        
        private string tipoDocumentoField;
        
        private string fechaVencimientoTarjetaField;
        
        private string valorCVV2Field;
        
        private string valorTransaccionField;
        
        private string numeroCuotasField;
        
        private string estadoField;
        
        private string pinblockActualField;
        
        private string pinblockNuevoField;
        
        private string filler1Field;
        
        private string filler2Field;
        
        private string filler3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoAplicacion {
            get {
                return this.codigoAplicacionField;
            }
            set {
                this.codigoAplicacionField = value;
                this.RaisePropertyChanged("codigoAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoProcesamiento {
            get {
                return this.codigoProcesamientoField;
            }
            set {
                this.codigoProcesamientoField = value;
                this.RaisePropertyChanged("codigoProcesamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string fechaTransaccion {
            get {
                return this.fechaTransaccionField;
            }
            set {
                this.fechaTransaccionField = value;
                this.RaisePropertyChanged("fechaTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string horaTransaccion {
            get {
                return this.horaTransaccionField;
            }
            set {
                this.horaTransaccionField = value;
                this.RaisePropertyChanged("horaTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fechaEfectiva {
            get {
                return this.fechaEfectivaField;
            }
            set {
                this.fechaEfectivaField = value;
                this.RaisePropertyChanged("fechaEfectiva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoCanal {
            get {
                return this.codigoCanalField;
            }
            set {
                this.codigoCanalField = value;
                this.RaisePropertyChanged("codigoCanal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string codigoSwitch {
            get {
                return this.codigoSwitchField;
            }
            set {
                this.codigoSwitchField = value;
                this.RaisePropertyChanged("codigoSwitch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string codigoDispositivo {
            get {
                return this.codigoDispositivoField;
            }
            set {
                this.codigoDispositivoField = value;
                this.RaisePropertyChanged("codigoDispositivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string consecutivo {
            get {
                return this.consecutivoField;
            }
            set {
                this.consecutivoField = value;
                this.RaisePropertyChanged("consecutivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string tipoTransaccion {
            get {
                return this.tipoTransaccionField;
            }
            set {
                this.tipoTransaccionField = value;
                this.RaisePropertyChanged("tipoTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string codigoEntidad {
            get {
                return this.codigoEntidadField;
            }
            set {
                this.codigoEntidadField = value;
                this.RaisePropertyChanged("codigoEntidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string passwordId {
            get {
                return this.passwordIdField;
            }
            set {
                this.passwordIdField = value;
                this.RaisePropertyChanged("passwordId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                this.numeroTarjetaField = value;
                this.RaisePropertyChanged("numeroTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string fechaVencimientoTarjeta {
            get {
                return this.fechaVencimientoTarjetaField;
            }
            set {
                this.fechaVencimientoTarjetaField = value;
                this.RaisePropertyChanged("fechaVencimientoTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string valorCVV2 {
            get {
                return this.valorCVV2Field;
            }
            set {
                this.valorCVV2Field = value;
                this.RaisePropertyChanged("valorCVV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string valorTransaccion {
            get {
                return this.valorTransaccionField;
            }
            set {
                this.valorTransaccionField = value;
                this.RaisePropertyChanged("valorTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string numeroCuotas {
            get {
                return this.numeroCuotasField;
            }
            set {
                this.numeroCuotasField = value;
                this.RaisePropertyChanged("numeroCuotas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string pinblockActual {
            get {
                return this.pinblockActualField;
            }
            set {
                this.pinblockActualField = value;
                this.RaisePropertyChanged("pinblockActual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string pinblockNuevo {
            get {
                return this.pinblockNuevoField;
            }
            set {
                this.pinblockNuevoField = value;
                this.RaisePropertyChanged("pinblockNuevo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string filler1 {
            get {
                return this.filler1Field;
            }
            set {
                this.filler1Field = value;
                this.RaisePropertyChanged("filler1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string filler2 {
            get {
                return this.filler2Field;
            }
            set {
                this.filler2Field = value;
                this.RaisePropertyChanged("filler2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string filler3 {
            get {
                return this.filler3Field;
            }
            set {
                this.filler3Field = value;
                this.RaisePropertyChanged("filler3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.transacciones.services.ws.asnetla.com/")]
    public partial class aplicarTransaccionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TransaccionAPPResponseDto aplicarTransaccionResponse1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aplicarTransaccionResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TransaccionAPPResponseDto aplicarTransaccionResponse1 {
            get {
                return this.aplicarTransaccionResponse1Field;
            }
            set {
                this.aplicarTransaccionResponse1Field = value;
                this.RaisePropertyChanged("aplicarTransaccionResponse1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.transacciones.services.ws.asnetla.com/")]
    public partial class TransaccionAPPResponseDto : TransaccionAPPDTO {
        
        private string numeroAutorizacionField;
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private string consecutivoRespuestaField;
        
        private string fillerRespuesta1Field;
        
        private string fillerRespuesta2Field;
        
        private string fillerRespuesta3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                this.numeroAutorizacionField = value;
                this.RaisePropertyChanged("numeroAutorizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                this.descripcionRespuestaField = value;
                this.RaisePropertyChanged("descripcionRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string consecutivoRespuesta {
            get {
                return this.consecutivoRespuestaField;
            }
            set {
                this.consecutivoRespuestaField = value;
                this.RaisePropertyChanged("consecutivoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fillerRespuesta1 {
            get {
                return this.fillerRespuesta1Field;
            }
            set {
                this.fillerRespuesta1Field = value;
                this.RaisePropertyChanged("fillerRespuesta1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string fillerRespuesta2 {
            get {
                return this.fillerRespuesta2Field;
            }
            set {
                this.fillerRespuesta2Field = value;
                this.RaisePropertyChanged("fillerRespuesta2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fillerRespuesta3 {
            get {
                return this.fillerRespuesta3Field;
            }
            set {
                this.fillerRespuesta3Field = value;
                this.RaisePropertyChanged("fillerRespuesta3");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AplicarTransaccionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.transacciones.services.ws.asnetla.com/", Order=0)]
        public BancaServices.AsNetSeguridadCVV2.aplicarTransaccionRequest aplicarTransaccionRequest;
        
        public AplicarTransaccionRequest1() {
        }
        
        public AplicarTransaccionRequest1(BancaServices.AsNetSeguridadCVV2.aplicarTransaccionRequest aplicarTransaccionRequest) {
            this.aplicarTransaccionRequest = aplicarTransaccionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AplicarTransaccionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.transacciones.services.ws.asnetla.com/", Order=0)]
        public BancaServices.AsNetSeguridadCVV2.aplicarTransaccionResponse aplicarTransaccionResponse;
        
        public AplicarTransaccionResponse1() {
        }
        
        public AplicarTransaccionResponse1(BancaServices.AsNetSeguridadCVV2.aplicarTransaccionResponse aplicarTransaccionResponse) {
            this.aplicarTransaccionResponse = aplicarTransaccionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransaccionesProxyChannel : BancaServices.AsNetSeguridadCVV2.TransaccionesProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransaccionesProxyClient : System.ServiceModel.ClientBase<BancaServices.AsNetSeguridadCVV2.TransaccionesProxy>, BancaServices.AsNetSeguridadCVV2.TransaccionesProxy {
        
        public TransaccionesProxyClient() {
        }
        
        public TransaccionesProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransaccionesProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaccionesProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaccionesProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.AsNetSeguridadCVV2.AplicarTransaccionResponse1 BancaServices.AsNetSeguridadCVV2.TransaccionesProxy.AplicarTransaccion(BancaServices.AsNetSeguridadCVV2.AplicarTransaccionRequest1 request) {
            return base.Channel.AplicarTransaccion(request);
        }
        
        public BancaServices.AsNetSeguridadCVV2.aplicarTransaccionResponse AplicarTransaccion(BancaServices.AsNetSeguridadCVV2.aplicarTransaccionRequest aplicarTransaccionRequest) {
            BancaServices.AsNetSeguridadCVV2.AplicarTransaccionRequest1 inValue = new BancaServices.AsNetSeguridadCVV2.AplicarTransaccionRequest1();
            inValue.aplicarTransaccionRequest = aplicarTransaccionRequest;
            BancaServices.AsNetSeguridadCVV2.AplicarTransaccionResponse1 retVal = ((BancaServices.AsNetSeguridadCVV2.TransaccionesProxy)(this)).AplicarTransaccion(inValue);
            return retVal.aplicarTransaccionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.AsNetSeguridadCVV2.AplicarTransaccionResponse1> BancaServices.AsNetSeguridadCVV2.TransaccionesProxy.AplicarTransaccionAsync(BancaServices.AsNetSeguridadCVV2.AplicarTransaccionRequest1 request) {
            return base.Channel.AplicarTransaccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.AsNetSeguridadCVV2.AplicarTransaccionResponse1> AplicarTransaccionAsync(BancaServices.AsNetSeguridadCVV2.aplicarTransaccionRequest aplicarTransaccionRequest) {
            BancaServices.AsNetSeguridadCVV2.AplicarTransaccionRequest1 inValue = new BancaServices.AsNetSeguridadCVV2.AplicarTransaccionRequest1();
            inValue.aplicarTransaccionRequest = aplicarTransaccionRequest;
            return ((BancaServices.AsNetSeguridadCVV2.TransaccionesProxy)(this)).AplicarTransaccionAsync(inValue);
        }
    }
}
