//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaServices.AsNetComprasSv {
    using System.Runtime.Serialization;
    
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraCarteraRequest_Dto", Namespace="http://schema.rbm.com")]
    [System.SerializableAttribute()]
    public partial class CompraCarteraRequest_Dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string canalNovedadField;
        
        private string codigoCanalField;
        
        private string codigoCentroTUYAField;
        
        private string codigoDispositivoField;
        
        private string codigoEntidadField;
        
        private string codigoEstablecimientoField;
        
        private string codigoSwitchField;
        
        private string fechaNovedadField;
        
        private string horaNovedadField;
        
        private string modoEntradaPOSField;
        
        private string numeroAutorizacionField;
        
        private string numeroCuotasField;
        
        private string numeroReferenciaField;
        
        private string numeroTarjetaField;
        
        private string terminalNovedadField;
        
        private string tipoProductoField;
        
        private string valorDevolucionField;
        
        private string valorIVAField;
        
        private string valorTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string canalNovedad {
            get {
                return this.canalNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.canalNovedadField, value) != true)) {
                    this.canalNovedadField = value;
                    this.RaisePropertyChanged("canalNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoCanal {
            get {
                return this.codigoCanalField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCanalField, value) != true)) {
                    this.codigoCanalField = value;
                    this.RaisePropertyChanged("codigoCanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoCentroTUYA {
            get {
                return this.codigoCentroTUYAField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCentroTUYAField, value) != true)) {
                    this.codigoCentroTUYAField = value;
                    this.RaisePropertyChanged("codigoCentroTUYA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoDispositivo {
            get {
                return this.codigoDispositivoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoDispositivoField, value) != true)) {
                    this.codigoDispositivoField = value;
                    this.RaisePropertyChanged("codigoDispositivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoEntidad {
            get {
                return this.codigoEntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoEntidadField, value) != true)) {
                    this.codigoEntidadField = value;
                    this.RaisePropertyChanged("codigoEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoEstablecimiento {
            get {
                return this.codigoEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoEstablecimientoField, value) != true)) {
                    this.codigoEstablecimientoField = value;
                    this.RaisePropertyChanged("codigoEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoSwitch {
            get {
                return this.codigoSwitchField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoSwitchField, value) != true)) {
                    this.codigoSwitchField = value;
                    this.RaisePropertyChanged("codigoSwitch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fechaNovedad {
            get {
                return this.fechaNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaNovedadField, value) != true)) {
                    this.fechaNovedadField = value;
                    this.RaisePropertyChanged("fechaNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string horaNovedad {
            get {
                return this.horaNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.horaNovedadField, value) != true)) {
                    this.horaNovedadField = value;
                    this.RaisePropertyChanged("horaNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string modoEntradaPOS {
            get {
                return this.modoEntradaPOSField;
            }
            set {
                if ((object.ReferenceEquals(this.modoEntradaPOSField, value) != true)) {
                    this.modoEntradaPOSField = value;
                    this.RaisePropertyChanged("modoEntradaPOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroAutorizacionField, value) != true)) {
                    this.numeroAutorizacionField = value;
                    this.RaisePropertyChanged("numeroAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroCuotas {
            get {
                return this.numeroCuotasField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroCuotasField, value) != true)) {
                    this.numeroCuotasField = value;
                    this.RaisePropertyChanged("numeroCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroReferencia {
            get {
                return this.numeroReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroReferenciaField, value) != true)) {
                    this.numeroReferenciaField = value;
                    this.RaisePropertyChanged("numeroReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroTarjetaField, value) != true)) {
                    this.numeroTarjetaField = value;
                    this.RaisePropertyChanged("numeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string terminalNovedad {
            get {
                return this.terminalNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.terminalNovedadField, value) != true)) {
                    this.terminalNovedadField = value;
                    this.RaisePropertyChanged("terminalNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoProductoField, value) != true)) {
                    this.tipoProductoField = value;
                    this.RaisePropertyChanged("tipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorDevolucion {
            get {
                return this.valorDevolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.valorDevolucionField, value) != true)) {
                    this.valorDevolucionField = value;
                    this.RaisePropertyChanged("valorDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorIVA {
            get {
                return this.valorIVAField;
            }
            set {
                if ((object.ReferenceEquals(this.valorIVAField, value) != true)) {
                    this.valorIVAField = value;
                    this.RaisePropertyChanged("valorIVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorTransaccion {
            get {
                return this.valorTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.valorTransaccionField, value) != true)) {
                    this.valorTransaccionField = value;
                    this.RaisePropertyChanged("valorTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraCreditoResponse_Dto", Namespace="http://schema.rbm.com")]
    [System.SerializableAttribute()]
    public partial class CompraCreditoResponse_Dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codigoRespuestaField;
        
        private string cupoDisponibleField;
        
        private string cupoTotalField;
        
        private string descripcionRespuestaField;
        
        private string fechaAutorizacionField;
        
        private string horaAutorizacionField;
        
        private string numeroAutorizacionField;
        
        private string valorComisionField;
        
        private string valorIVAComisionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoRespuestaField, value) != true)) {
                    this.codigoRespuestaField = value;
                    this.RaisePropertyChanged("codigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cupoDisponible {
            get {
                return this.cupoDisponibleField;
            }
            set {
                if ((object.ReferenceEquals(this.cupoDisponibleField, value) != true)) {
                    this.cupoDisponibleField = value;
                    this.RaisePropertyChanged("cupoDisponible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cupoTotal {
            get {
                return this.cupoTotalField;
            }
            set {
                if ((object.ReferenceEquals(this.cupoTotalField, value) != true)) {
                    this.cupoTotalField = value;
                    this.RaisePropertyChanged("cupoTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionRespuestaField, value) != true)) {
                    this.descripcionRespuestaField = value;
                    this.RaisePropertyChanged("descripcionRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fechaAutorizacion {
            get {
                return this.fechaAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaAutorizacionField, value) != true)) {
                    this.fechaAutorizacionField = value;
                    this.RaisePropertyChanged("fechaAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string horaAutorizacion {
            get {
                return this.horaAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.horaAutorizacionField, value) != true)) {
                    this.horaAutorizacionField = value;
                    this.RaisePropertyChanged("horaAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroAutorizacionField, value) != true)) {
                    this.numeroAutorizacionField = value;
                    this.RaisePropertyChanged("numeroAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorComision {
            get {
                return this.valorComisionField;
            }
            set {
                if ((object.ReferenceEquals(this.valorComisionField, value) != true)) {
                    this.valorComisionField = value;
                    this.RaisePropertyChanged("valorComision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorIVAComision {
            get {
                return this.valorIVAComisionField;
            }
            set {
                if ((object.ReferenceEquals(this.valorIVAComisionField, value) != true)) {
                    this.valorIVAComisionField = value;
                    this.RaisePropertyChanged("valorIVAComision");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraCreditoRequest_Dto", Namespace="http://schema.rbm.com")]
    [System.SerializableAttribute()]
    public partial class CompraCreditoRequest_Dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string canalNovedadField;
        
        private string codConvenioField;
        
        private string codigoCanalField;
        
        private string codigoCentroTUYAField;
        
        private string codigoDispositivoField;
        
        private string codigoEntidadField;
        
        private string codigoEstablecimientoField;
        
        private string codigoMCCField;
        
        private string codigoSwitchField;
        
        private string codigoTransaccionField;
        
        private string cvc2Field;
        
        private string descripcionOperacionField;
        
        private string descuentoTransaccionField;
        
        private string fechaNovedadField;
        
        private string fechaVencimientoField;
        
        private string filler1TrackField;
        
        private string filler2TrackField;
        
        private string horaNovedadField;
        
        private string modoEntradaPOSField;
        
        private string numeroAutorizacionField;
        
        private string numeroCuotasField;
        
        private string numeroReferenciaField;
        
        private string numeroTarjetaField;
        
        private string origenTransaccionField;
        
        private string pinblockField;
        
        private string terminalNovedadField;
        
        private string tipoProductoField;
        
        private string valorDevolucionField;
        
        private string valorIVAField;
        
        private string valorPropinaField;
        
        private string valorTransaccionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string canalNovedad {
            get {
                return this.canalNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.canalNovedadField, value) != true)) {
                    this.canalNovedadField = value;
                    this.RaisePropertyChanged("canalNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codConvenio {
            get {
                return this.codConvenioField;
            }
            set {
                if ((object.ReferenceEquals(this.codConvenioField, value) != true)) {
                    this.codConvenioField = value;
                    this.RaisePropertyChanged("codConvenio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoCanal {
            get {
                return this.codigoCanalField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCanalField, value) != true)) {
                    this.codigoCanalField = value;
                    this.RaisePropertyChanged("codigoCanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoCentroTUYA {
            get {
                return this.codigoCentroTUYAField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCentroTUYAField, value) != true)) {
                    this.codigoCentroTUYAField = value;
                    this.RaisePropertyChanged("codigoCentroTUYA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoDispositivo {
            get {
                return this.codigoDispositivoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoDispositivoField, value) != true)) {
                    this.codigoDispositivoField = value;
                    this.RaisePropertyChanged("codigoDispositivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoEntidad {
            get {
                return this.codigoEntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoEntidadField, value) != true)) {
                    this.codigoEntidadField = value;
                    this.RaisePropertyChanged("codigoEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoEstablecimiento {
            get {
                return this.codigoEstablecimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoEstablecimientoField, value) != true)) {
                    this.codigoEstablecimientoField = value;
                    this.RaisePropertyChanged("codigoEstablecimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoMCC {
            get {
                return this.codigoMCCField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoMCCField, value) != true)) {
                    this.codigoMCCField = value;
                    this.RaisePropertyChanged("codigoMCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoSwitch {
            get {
                return this.codigoSwitchField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoSwitchField, value) != true)) {
                    this.codigoSwitchField = value;
                    this.RaisePropertyChanged("codigoSwitch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoTransaccion {
            get {
                return this.codigoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoTransaccionField, value) != true)) {
                    this.codigoTransaccionField = value;
                    this.RaisePropertyChanged("codigoTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cvc2 {
            get {
                return this.cvc2Field;
            }
            set {
                if ((object.ReferenceEquals(this.cvc2Field, value) != true)) {
                    this.cvc2Field = value;
                    this.RaisePropertyChanged("cvc2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descripcionOperacion {
            get {
                return this.descripcionOperacionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionOperacionField, value) != true)) {
                    this.descripcionOperacionField = value;
                    this.RaisePropertyChanged("descripcionOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descuentoTransaccion {
            get {
                return this.descuentoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.descuentoTransaccionField, value) != true)) {
                    this.descuentoTransaccionField = value;
                    this.RaisePropertyChanged("descuentoTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fechaNovedad {
            get {
                return this.fechaNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaNovedadField, value) != true)) {
                    this.fechaNovedadField = value;
                    this.RaisePropertyChanged("fechaNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaVencimientoField, value) != true)) {
                    this.fechaVencimientoField = value;
                    this.RaisePropertyChanged("fechaVencimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string filler1Track {
            get {
                return this.filler1TrackField;
            }
            set {
                if ((object.ReferenceEquals(this.filler1TrackField, value) != true)) {
                    this.filler1TrackField = value;
                    this.RaisePropertyChanged("filler1Track");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string filler2Track {
            get {
                return this.filler2TrackField;
            }
            set {
                if ((object.ReferenceEquals(this.filler2TrackField, value) != true)) {
                    this.filler2TrackField = value;
                    this.RaisePropertyChanged("filler2Track");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string horaNovedad {
            get {
                return this.horaNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.horaNovedadField, value) != true)) {
                    this.horaNovedadField = value;
                    this.RaisePropertyChanged("horaNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string modoEntradaPOS {
            get {
                return this.modoEntradaPOSField;
            }
            set {
                if ((object.ReferenceEquals(this.modoEntradaPOSField, value) != true)) {
                    this.modoEntradaPOSField = value;
                    this.RaisePropertyChanged("modoEntradaPOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroAutorizacionField, value) != true)) {
                    this.numeroAutorizacionField = value;
                    this.RaisePropertyChanged("numeroAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroCuotas {
            get {
                return this.numeroCuotasField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroCuotasField, value) != true)) {
                    this.numeroCuotasField = value;
                    this.RaisePropertyChanged("numeroCuotas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroReferencia {
            get {
                return this.numeroReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroReferenciaField, value) != true)) {
                    this.numeroReferenciaField = value;
                    this.RaisePropertyChanged("numeroReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroTarjetaField, value) != true)) {
                    this.numeroTarjetaField = value;
                    this.RaisePropertyChanged("numeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string origenTransaccion {
            get {
                return this.origenTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.origenTransaccionField, value) != true)) {
                    this.origenTransaccionField = value;
                    this.RaisePropertyChanged("origenTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string pinblock {
            get {
                return this.pinblockField;
            }
            set {
                if ((object.ReferenceEquals(this.pinblockField, value) != true)) {
                    this.pinblockField = value;
                    this.RaisePropertyChanged("pinblock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string terminalNovedad {
            get {
                return this.terminalNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.terminalNovedadField, value) != true)) {
                    this.terminalNovedadField = value;
                    this.RaisePropertyChanged("terminalNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoProductoField, value) != true)) {
                    this.tipoProductoField = value;
                    this.RaisePropertyChanged("tipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorDevolucion {
            get {
                return this.valorDevolucionField;
            }
            set {
                if ((object.ReferenceEquals(this.valorDevolucionField, value) != true)) {
                    this.valorDevolucionField = value;
                    this.RaisePropertyChanged("valorDevolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorIVA {
            get {
                return this.valorIVAField;
            }
            set {
                if ((object.ReferenceEquals(this.valorIVAField, value) != true)) {
                    this.valorIVAField = value;
                    this.RaisePropertyChanged("valorIVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorPropina {
            get {
                return this.valorPropinaField;
            }
            set {
                if ((object.ReferenceEquals(this.valorPropinaField, value) != true)) {
                    this.valorPropinaField = value;
                    this.RaisePropertyChanged("valorPropina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorTransaccion {
            get {
                return this.valorTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.valorTransaccionField, value) != true)) {
                    this.valorTransaccionField = value;
                    this.RaisePropertyChanged("valorTransaccion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsdl.rbm.com", ConfigurationName="AsNetComprasSv.CompraCreditoBPO_WS")]
    public interface CompraCreditoBPO_WS {
        
        // CODEGEN: Generating message contract since element name usrId from namespace http://wsdl.rbm.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        BancaServices.AsNetComprasSv.compraCarteraLineaResponse compraCarteraLinea(BancaServices.AsNetComprasSv.compraCarteraLineaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.compraCarteraLineaResponse> compraCarteraLineaAsync(BancaServices.AsNetComprasSv.compraCarteraLineaRequest request);
        
        // CODEGEN: Generating message contract since element name usrId from namespace http://wsdl.rbm.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        BancaServices.AsNetComprasSv.anularCompraCarteraLineaResponse anularCompraCarteraLinea(BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.anularCompraCarteraLineaResponse> anularCompraCarteraLineaAsync(BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequest request);
        
        // CODEGEN: Generating message contract since element name usrId from namespace http://wsdl.rbm.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        BancaServices.AsNetComprasSv.compraCreditoLineaResponse compraCreditoLinea(BancaServices.AsNetComprasSv.compraCreditoLineaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.compraCreditoLineaResponse> compraCreditoLineaAsync(BancaServices.AsNetComprasSv.compraCreditoLineaRequest request);
        
        // CODEGEN: Generating message contract since element name usrId from namespace http://wsdl.rbm.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        BancaServices.AsNetComprasSv.anularCompraCreditoLineaResponse anularCompraCreditoLinea(BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.anularCompraCreditoLineaResponse> anularCompraCreditoLineaAsync(BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class compraCarteraLineaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="compraCarteraLinea", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.AsNetComprasSv.compraCarteraLineaRequestBody Body;
        
        public compraCarteraLineaRequest() {
        }
        
        public compraCarteraLineaRequest(BancaServices.AsNetComprasSv.compraCarteraLineaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class compraCarteraLineaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usrId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usrPsw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BancaServices.AsNetComprasSv.CompraCarteraRequest_Dto requestDto;
        
        public compraCarteraLineaRequestBody() {
        }
        
        public compraCarteraLineaRequestBody(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCarteraRequest_Dto requestDto) {
            this.usrId = usrId;
            this.usrPsw = usrPsw;
            this.requestDto = requestDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class compraCarteraLineaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="compraCarteraLineaResponse", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.AsNetComprasSv.compraCarteraLineaResponseBody Body;
        
        public compraCarteraLineaResponse() {
        }
        
        public compraCarteraLineaResponse(BancaServices.AsNetComprasSv.compraCarteraLineaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class compraCarteraLineaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto compraCarteraLineaReturn;
        
        public compraCarteraLineaResponseBody() {
        }
        
        public compraCarteraLineaResponseBody(BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto compraCarteraLineaReturn) {
            this.compraCarteraLineaReturn = compraCarteraLineaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anularCompraCarteraLineaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anularCompraCarteraLinea", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequestBody Body;
        
        public anularCompraCarteraLineaRequest() {
        }
        
        public anularCompraCarteraLineaRequest(BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class anularCompraCarteraLineaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usrId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usrPsw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BancaServices.AsNetComprasSv.CompraCarteraRequest_Dto requestDto;
        
        public anularCompraCarteraLineaRequestBody() {
        }
        
        public anularCompraCarteraLineaRequestBody(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCarteraRequest_Dto requestDto) {
            this.usrId = usrId;
            this.usrPsw = usrPsw;
            this.requestDto = requestDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anularCompraCarteraLineaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anularCompraCarteraLineaResponse", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.AsNetComprasSv.anularCompraCarteraLineaResponseBody Body;
        
        public anularCompraCarteraLineaResponse() {
        }
        
        public anularCompraCarteraLineaResponse(BancaServices.AsNetComprasSv.anularCompraCarteraLineaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class anularCompraCarteraLineaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto anularCompraCarteraLineaReturn;
        
        public anularCompraCarteraLineaResponseBody() {
        }
        
        public anularCompraCarteraLineaResponseBody(BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto anularCompraCarteraLineaReturn) {
            this.anularCompraCarteraLineaReturn = anularCompraCarteraLineaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class compraCreditoLineaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="compraCreditoLinea", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.AsNetComprasSv.compraCreditoLineaRequestBody Body;
        
        public compraCreditoLineaRequest() {
        }
        
        public compraCreditoLineaRequest(BancaServices.AsNetComprasSv.compraCreditoLineaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class compraCreditoLineaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usrId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usrPsw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BancaServices.AsNetComprasSv.CompraCreditoRequest_Dto requestDto;
        
        public compraCreditoLineaRequestBody() {
        }
        
        public compraCreditoLineaRequestBody(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCreditoRequest_Dto requestDto) {
            this.usrId = usrId;
            this.usrPsw = usrPsw;
            this.requestDto = requestDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class compraCreditoLineaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="compraCreditoLineaResponse", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.AsNetComprasSv.compraCreditoLineaResponseBody Body;
        
        public compraCreditoLineaResponse() {
        }
        
        public compraCreditoLineaResponse(BancaServices.AsNetComprasSv.compraCreditoLineaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class compraCreditoLineaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto compraCreditoLineaReturn;
        
        public compraCreditoLineaResponseBody() {
        }
        
        public compraCreditoLineaResponseBody(BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto compraCreditoLineaReturn) {
            this.compraCreditoLineaReturn = compraCreditoLineaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anularCompraCreditoLineaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anularCompraCreditoLinea", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequestBody Body;
        
        public anularCompraCreditoLineaRequest() {
        }
        
        public anularCompraCreditoLineaRequest(BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class anularCompraCreditoLineaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usrId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usrPsw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public BancaServices.AsNetComprasSv.CompraCreditoRequest_Dto requestDto;
        
        public anularCompraCreditoLineaRequestBody() {
        }
        
        public anularCompraCreditoLineaRequestBody(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCreditoRequest_Dto requestDto) {
            this.usrId = usrId;
            this.usrPsw = usrPsw;
            this.requestDto = requestDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anularCompraCreditoLineaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anularCompraCreditoLineaResponse", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.AsNetComprasSv.anularCompraCreditoLineaResponseBody Body;
        
        public anularCompraCreditoLineaResponse() {
        }
        
        public anularCompraCreditoLineaResponse(BancaServices.AsNetComprasSv.anularCompraCreditoLineaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class anularCompraCreditoLineaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto anularCompraCreditoLineaReturn;
        
        public anularCompraCreditoLineaResponseBody() {
        }
        
        public anularCompraCreditoLineaResponseBody(BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto anularCompraCreditoLineaReturn) {
            this.anularCompraCreditoLineaReturn = anularCompraCreditoLineaReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompraCreditoBPO_WSChannel : BancaServices.AsNetComprasSv.CompraCreditoBPO_WS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompraCreditoBPO_WSClient : System.ServiceModel.ClientBase<BancaServices.AsNetComprasSv.CompraCreditoBPO_WS>, BancaServices.AsNetComprasSv.CompraCreditoBPO_WS {
        
        public CompraCreditoBPO_WSClient() {
        }
        
        public CompraCreditoBPO_WSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompraCreditoBPO_WSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompraCreditoBPO_WSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompraCreditoBPO_WSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.AsNetComprasSv.compraCarteraLineaResponse BancaServices.AsNetComprasSv.CompraCreditoBPO_WS.compraCarteraLinea(BancaServices.AsNetComprasSv.compraCarteraLineaRequest request) {
            return base.Channel.compraCarteraLinea(request);
        }
        
        public BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto compraCarteraLinea(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCarteraRequest_Dto requestDto) {
            BancaServices.AsNetComprasSv.compraCarteraLineaRequest inValue = new BancaServices.AsNetComprasSv.compraCarteraLineaRequest();
            inValue.Body = new BancaServices.AsNetComprasSv.compraCarteraLineaRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.requestDto = requestDto;
            BancaServices.AsNetComprasSv.compraCarteraLineaResponse retVal = ((BancaServices.AsNetComprasSv.CompraCreditoBPO_WS)(this)).compraCarteraLinea(inValue);
            return retVal.Body.compraCarteraLineaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.compraCarteraLineaResponse> BancaServices.AsNetComprasSv.CompraCreditoBPO_WS.compraCarteraLineaAsync(BancaServices.AsNetComprasSv.compraCarteraLineaRequest request) {
            return base.Channel.compraCarteraLineaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.compraCarteraLineaResponse> compraCarteraLineaAsync(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCarteraRequest_Dto requestDto) {
            BancaServices.AsNetComprasSv.compraCarteraLineaRequest inValue = new BancaServices.AsNetComprasSv.compraCarteraLineaRequest();
            inValue.Body = new BancaServices.AsNetComprasSv.compraCarteraLineaRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.requestDto = requestDto;
            return ((BancaServices.AsNetComprasSv.CompraCreditoBPO_WS)(this)).compraCarteraLineaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.AsNetComprasSv.anularCompraCarteraLineaResponse BancaServices.AsNetComprasSv.CompraCreditoBPO_WS.anularCompraCarteraLinea(BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequest request) {
            return base.Channel.anularCompraCarteraLinea(request);
        }
        
        public BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto anularCompraCarteraLinea(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCarteraRequest_Dto requestDto) {
            BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequest inValue = new BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequest();
            inValue.Body = new BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.requestDto = requestDto;
            BancaServices.AsNetComprasSv.anularCompraCarteraLineaResponse retVal = ((BancaServices.AsNetComprasSv.CompraCreditoBPO_WS)(this)).anularCompraCarteraLinea(inValue);
            return retVal.Body.anularCompraCarteraLineaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.anularCompraCarteraLineaResponse> BancaServices.AsNetComprasSv.CompraCreditoBPO_WS.anularCompraCarteraLineaAsync(BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequest request) {
            return base.Channel.anularCompraCarteraLineaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.anularCompraCarteraLineaResponse> anularCompraCarteraLineaAsync(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCarteraRequest_Dto requestDto) {
            BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequest inValue = new BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequest();
            inValue.Body = new BancaServices.AsNetComprasSv.anularCompraCarteraLineaRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.requestDto = requestDto;
            return ((BancaServices.AsNetComprasSv.CompraCreditoBPO_WS)(this)).anularCompraCarteraLineaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.AsNetComprasSv.compraCreditoLineaResponse BancaServices.AsNetComprasSv.CompraCreditoBPO_WS.compraCreditoLinea(BancaServices.AsNetComprasSv.compraCreditoLineaRequest request) {
            return base.Channel.compraCreditoLinea(request);
        }
        
        public BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto compraCreditoLinea(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCreditoRequest_Dto requestDto) {
            BancaServices.AsNetComprasSv.compraCreditoLineaRequest inValue = new BancaServices.AsNetComprasSv.compraCreditoLineaRequest();
            inValue.Body = new BancaServices.AsNetComprasSv.compraCreditoLineaRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.requestDto = requestDto;
            BancaServices.AsNetComprasSv.compraCreditoLineaResponse retVal = ((BancaServices.AsNetComprasSv.CompraCreditoBPO_WS)(this)).compraCreditoLinea(inValue);
            return retVal.Body.compraCreditoLineaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.compraCreditoLineaResponse> BancaServices.AsNetComprasSv.CompraCreditoBPO_WS.compraCreditoLineaAsync(BancaServices.AsNetComprasSv.compraCreditoLineaRequest request) {
            return base.Channel.compraCreditoLineaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.compraCreditoLineaResponse> compraCreditoLineaAsync(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCreditoRequest_Dto requestDto) {
            BancaServices.AsNetComprasSv.compraCreditoLineaRequest inValue = new BancaServices.AsNetComprasSv.compraCreditoLineaRequest();
            inValue.Body = new BancaServices.AsNetComprasSv.compraCreditoLineaRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.requestDto = requestDto;
            return ((BancaServices.AsNetComprasSv.CompraCreditoBPO_WS)(this)).compraCreditoLineaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.AsNetComprasSv.anularCompraCreditoLineaResponse BancaServices.AsNetComprasSv.CompraCreditoBPO_WS.anularCompraCreditoLinea(BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequest request) {
            return base.Channel.anularCompraCreditoLinea(request);
        }
        
        public BancaServices.AsNetComprasSv.CompraCreditoResponse_Dto anularCompraCreditoLinea(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCreditoRequest_Dto requestDto) {
            BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequest inValue = new BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequest();
            inValue.Body = new BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.requestDto = requestDto;
            BancaServices.AsNetComprasSv.anularCompraCreditoLineaResponse retVal = ((BancaServices.AsNetComprasSv.CompraCreditoBPO_WS)(this)).anularCompraCreditoLinea(inValue);
            return retVal.Body.anularCompraCreditoLineaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.anularCompraCreditoLineaResponse> BancaServices.AsNetComprasSv.CompraCreditoBPO_WS.anularCompraCreditoLineaAsync(BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequest request) {
            return base.Channel.anularCompraCreditoLineaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.AsNetComprasSv.anularCompraCreditoLineaResponse> anularCompraCreditoLineaAsync(string usrId, string usrPsw, BancaServices.AsNetComprasSv.CompraCreditoRequest_Dto requestDto) {
            BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequest inValue = new BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequest();
            inValue.Body = new BancaServices.AsNetComprasSv.anularCompraCreditoLineaRequestBody();
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            inValue.Body.requestDto = requestDto;
            return ((BancaServices.AsNetComprasSv.CompraCreditoBPO_WS)(this)).anularCompraCreditoLineaAsync(inValue);
        }
    }
}
