//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaServices.NovedadesBloqueoSR {
    using System.Runtime.Serialization;
    
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NovedadNoMon_Dto", Namespace="http://schema.rbm.com")]
    [System.SerializableAttribute()]
    public partial class NovedadNoMon_Dto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string actividadEconomicaField;
        
        private string afinidadTarjetaField;
        
        private string binField;
        
        private string cicloFacturacionField;
        
        private string codigoEntidadField;
        
        private string codigoBancoDebitoAutomaticoField;
        
        private string codigoBarrasField;
        
        private string codigoBarrasConvenioMercadeoField;
        
        private string codigoBloqueoTarjetaField;
        
        private string codigoCanalField;
        
        private string codigoCiudadDireccionCorrespondenciaField;
        
        private string codigoCiudadDireccionResidencialField;
        
        private string codigoDepartamentoCorrespondenciaField;
        
        private string codigoDepartamentoDireccionResidencial1Field;
        
        private string codigoOficinaDistribucionPlasticoField;
        
        private string codigoPuntoDistribucionField;
        
        private string codigoRespuestaField;
        
        private string codigoVendedorField;
        
        private string correoElectronicoField;
        
        private string cupoAsignadoField;
        
        private string descripcionRespuestaField;
        
        private string direccionCorrespondenciaLinea1Field;
        
        private string direccionCorrespondenciaLinea2Field;
        
        private string direccionResidencialLinea1Field;
        
        private string direccionResidencialLinea2Field;
        
        private string estadoCivilField;
        
        private string estadoRegistroRecibidoField;
        
        private string fechaCesacionCausacionField;
        
        private string fechaNacimientoField;
        
        private string fechaSolicitudField;
        
        private string fillerField;
        
        private string grupoManejoField;
        
        private string indicadorCesacionCausacionField;
        
        private string indicadorDebitoAutomaticoField;
        
        private string indicativoCiudadField;
        
        private string motivoBloqueoField;
        
        private string nitField;
        
        private string nombreLargoField;
        
        private string nombreRealceField;
        
        private string numeroCuentaDebitoAutomaticoField;
        
        private string numeroIdAmparadorField;
        
        private string numeroIdentificacionField;
        
        private string numeroProductoReferenciaCruzadaField;
        
        private string numeroReferenciaField;
        
        private string numeroSolicitudField;
        
        private string numeroTarjetaAsignadoField;
        
        private string oficinaRadicacionSolicitudField;
        
        private string origenIngresosField;
        
        private string primerApellidoField;
        
        private string primerNombreField;
        
        private string segundoApellidoField;
        
        private string segundoNombreField;
        
        private string sexoField;
        
        private string subtipoField;
        
        private string tarjetaAnteriorField;
        
        private string telefonoOficinaField;
        
        private string telefonoResidenciaField;
        
        private string tipoCuentaField;
        
        private string tipoCuentaDebitoAutomaticoField;
        
        private string tipoIdAmparadorField;
        
        private string tipoIdentificacionField;
        
        private string tipoNovedadField;
        
        private string tipoPersonaField;
        
        private string tipoSolicitudField;
        
        private string tipoTarjetaField;
        
        private string valorCuotaFijaField;
        
        private string zonaPostalDireccionCorrespondenciaField;
        
        private string zonaPostalDireccionResidencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string actividadEconomica {
            get {
                return this.actividadEconomicaField;
            }
            set {
                if ((object.ReferenceEquals(this.actividadEconomicaField, value) != true)) {
                    this.actividadEconomicaField = value;
                    this.RaisePropertyChanged("actividadEconomica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string afinidadTarjeta {
            get {
                return this.afinidadTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.afinidadTarjetaField, value) != true)) {
                    this.afinidadTarjetaField = value;
                    this.RaisePropertyChanged("afinidadTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string bin {
            get {
                return this.binField;
            }
            set {
                if ((object.ReferenceEquals(this.binField, value) != true)) {
                    this.binField = value;
                    this.RaisePropertyChanged("bin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string cicloFacturacion {
            get {
                return this.cicloFacturacionField;
            }
            set {
                if ((object.ReferenceEquals(this.cicloFacturacionField, value) != true)) {
                    this.cicloFacturacionField = value;
                    this.RaisePropertyChanged("cicloFacturacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoEntidad {
            get {
                return this.codigoEntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoEntidadField, value) != true)) {
                    this.codigoEntidadField = value;
                    this.RaisePropertyChanged("codigoEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string codigoBancoDebitoAutomatico {
            get {
                return this.codigoBancoDebitoAutomaticoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoBancoDebitoAutomaticoField, value) != true)) {
                    this.codigoBancoDebitoAutomaticoField = value;
                    this.RaisePropertyChanged("codigoBancoDebitoAutomatico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string codigoBarras {
            get {
                return this.codigoBarrasField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoBarrasField, value) != true)) {
                    this.codigoBarrasField = value;
                    this.RaisePropertyChanged("codigoBarras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string codigoBarrasConvenioMercadeo {
            get {
                return this.codigoBarrasConvenioMercadeoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoBarrasConvenioMercadeoField, value) != true)) {
                    this.codigoBarrasConvenioMercadeoField = value;
                    this.RaisePropertyChanged("codigoBarrasConvenioMercadeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public string codigoBloqueoTarjeta {
            get {
                return this.codigoBloqueoTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoBloqueoTarjetaField, value) != true)) {
                    this.codigoBloqueoTarjetaField = value;
                    this.RaisePropertyChanged("codigoBloqueoTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public string codigoCanal {
            get {
                return this.codigoCanalField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCanalField, value) != true)) {
                    this.codigoCanalField = value;
                    this.RaisePropertyChanged("codigoCanal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string codigoCiudadDireccionCorrespondencia {
            get {
                return this.codigoCiudadDireccionCorrespondenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCiudadDireccionCorrespondenciaField, value) != true)) {
                    this.codigoCiudadDireccionCorrespondenciaField = value;
                    this.RaisePropertyChanged("codigoCiudadDireccionCorrespondencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public string codigoCiudadDireccionResidencial {
            get {
                return this.codigoCiudadDireccionResidencialField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoCiudadDireccionResidencialField, value) != true)) {
                    this.codigoCiudadDireccionResidencialField = value;
                    this.RaisePropertyChanged("codigoCiudadDireccionResidencial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public string codigoDepartamentoCorrespondencia {
            get {
                return this.codigoDepartamentoCorrespondenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoDepartamentoCorrespondenciaField, value) != true)) {
                    this.codigoDepartamentoCorrespondenciaField = value;
                    this.RaisePropertyChanged("codigoDepartamentoCorrespondencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public string codigoDepartamentoDireccionResidencial1 {
            get {
                return this.codigoDepartamentoDireccionResidencial1Field;
            }
            set {
                if ((object.ReferenceEquals(this.codigoDepartamentoDireccionResidencial1Field, value) != true)) {
                    this.codigoDepartamentoDireccionResidencial1Field = value;
                    this.RaisePropertyChanged("codigoDepartamentoDireccionResidencial1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public string codigoOficinaDistribucionPlastico {
            get {
                return this.codigoOficinaDistribucionPlasticoField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoOficinaDistribucionPlasticoField, value) != true)) {
                    this.codigoOficinaDistribucionPlasticoField = value;
                    this.RaisePropertyChanged("codigoOficinaDistribucionPlastico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public string codigoPuntoDistribucion {
            get {
                return this.codigoPuntoDistribucionField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoPuntoDistribucionField, value) != true)) {
                    this.codigoPuntoDistribucionField = value;
                    this.RaisePropertyChanged("codigoPuntoDistribucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoRespuestaField, value) != true)) {
                    this.codigoRespuestaField = value;
                    this.RaisePropertyChanged("codigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public string codigoVendedor {
            get {
                return this.codigoVendedorField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoVendedorField, value) != true)) {
                    this.codigoVendedorField = value;
                    this.RaisePropertyChanged("codigoVendedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoElectronicoField, value) != true)) {
                    this.correoElectronicoField = value;
                    this.RaisePropertyChanged("correoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public string cupoAsignado {
            get {
                return this.cupoAsignadoField;
            }
            set {
                if ((object.ReferenceEquals(this.cupoAsignadoField, value) != true)) {
                    this.cupoAsignadoField = value;
                    this.RaisePropertyChanged("cupoAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionRespuestaField, value) != true)) {
                    this.descripcionRespuestaField = value;
                    this.RaisePropertyChanged("descripcionRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public string direccionCorrespondenciaLinea1 {
            get {
                return this.direccionCorrespondenciaLinea1Field;
            }
            set {
                if ((object.ReferenceEquals(this.direccionCorrespondenciaLinea1Field, value) != true)) {
                    this.direccionCorrespondenciaLinea1Field = value;
                    this.RaisePropertyChanged("direccionCorrespondenciaLinea1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public string direccionCorrespondenciaLinea2 {
            get {
                return this.direccionCorrespondenciaLinea2Field;
            }
            set {
                if ((object.ReferenceEquals(this.direccionCorrespondenciaLinea2Field, value) != true)) {
                    this.direccionCorrespondenciaLinea2Field = value;
                    this.RaisePropertyChanged("direccionCorrespondenciaLinea2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public string direccionResidencialLinea1 {
            get {
                return this.direccionResidencialLinea1Field;
            }
            set {
                if ((object.ReferenceEquals(this.direccionResidencialLinea1Field, value) != true)) {
                    this.direccionResidencialLinea1Field = value;
                    this.RaisePropertyChanged("direccionResidencialLinea1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public string direccionResidencialLinea2 {
            get {
                return this.direccionResidencialLinea2Field;
            }
            set {
                if ((object.ReferenceEquals(this.direccionResidencialLinea2Field, value) != true)) {
                    this.direccionResidencialLinea2Field = value;
                    this.RaisePropertyChanged("direccionResidencialLinea2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=25)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoCivilField, value) != true)) {
                    this.estadoCivilField = value;
                    this.RaisePropertyChanged("estadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public string estadoRegistroRecibido {
            get {
                return this.estadoRegistroRecibidoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoRegistroRecibidoField, value) != true)) {
                    this.estadoRegistroRecibidoField = value;
                    this.RaisePropertyChanged("estadoRegistroRecibido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=27)]
        public string fechaCesacionCausacion {
            get {
                return this.fechaCesacionCausacionField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaCesacionCausacionField, value) != true)) {
                    this.fechaCesacionCausacionField = value;
                    this.RaisePropertyChanged("fechaCesacionCausacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=28)]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaNacimientoField, value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public string fechaSolicitud {
            get {
                return this.fechaSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaSolicitudField, value) != true)) {
                    this.fechaSolicitudField = value;
                    this.RaisePropertyChanged("fechaSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public string filler {
            get {
                return this.fillerField;
            }
            set {
                if ((object.ReferenceEquals(this.fillerField, value) != true)) {
                    this.fillerField = value;
                    this.RaisePropertyChanged("filler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=31)]
        public string grupoManejo {
            get {
                return this.grupoManejoField;
            }
            set {
                if ((object.ReferenceEquals(this.grupoManejoField, value) != true)) {
                    this.grupoManejoField = value;
                    this.RaisePropertyChanged("grupoManejo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=32)]
        public string indicadorCesacionCausacion {
            get {
                return this.indicadorCesacionCausacionField;
            }
            set {
                if ((object.ReferenceEquals(this.indicadorCesacionCausacionField, value) != true)) {
                    this.indicadorCesacionCausacionField = value;
                    this.RaisePropertyChanged("indicadorCesacionCausacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=33)]
        public string indicadorDebitoAutomatico {
            get {
                return this.indicadorDebitoAutomaticoField;
            }
            set {
                if ((object.ReferenceEquals(this.indicadorDebitoAutomaticoField, value) != true)) {
                    this.indicadorDebitoAutomaticoField = value;
                    this.RaisePropertyChanged("indicadorDebitoAutomatico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=34)]
        public string indicativoCiudad {
            get {
                return this.indicativoCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.indicativoCiudadField, value) != true)) {
                    this.indicativoCiudadField = value;
                    this.RaisePropertyChanged("indicativoCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=35)]
        public string motivoBloqueo {
            get {
                return this.motivoBloqueoField;
            }
            set {
                if ((object.ReferenceEquals(this.motivoBloqueoField, value) != true)) {
                    this.motivoBloqueoField = value;
                    this.RaisePropertyChanged("motivoBloqueo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=36)]
        public string nit {
            get {
                return this.nitField;
            }
            set {
                if ((object.ReferenceEquals(this.nitField, value) != true)) {
                    this.nitField = value;
                    this.RaisePropertyChanged("nit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=37)]
        public string nombreLargo {
            get {
                return this.nombreLargoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreLargoField, value) != true)) {
                    this.nombreLargoField = value;
                    this.RaisePropertyChanged("nombreLargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=38)]
        public string nombreRealce {
            get {
                return this.nombreRealceField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreRealceField, value) != true)) {
                    this.nombreRealceField = value;
                    this.RaisePropertyChanged("nombreRealce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=39)]
        public string numeroCuentaDebitoAutomatico {
            get {
                return this.numeroCuentaDebitoAutomaticoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroCuentaDebitoAutomaticoField, value) != true)) {
                    this.numeroCuentaDebitoAutomaticoField = value;
                    this.RaisePropertyChanged("numeroCuentaDebitoAutomatico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=40)]
        public string numeroIdAmparador {
            get {
                return this.numeroIdAmparadorField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroIdAmparadorField, value) != true)) {
                    this.numeroIdAmparadorField = value;
                    this.RaisePropertyChanged("numeroIdAmparador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=41)]
        public string numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroIdentificacionField, value) != true)) {
                    this.numeroIdentificacionField = value;
                    this.RaisePropertyChanged("numeroIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=42)]
        public string numeroProductoReferenciaCruzada {
            get {
                return this.numeroProductoReferenciaCruzadaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroProductoReferenciaCruzadaField, value) != true)) {
                    this.numeroProductoReferenciaCruzadaField = value;
                    this.RaisePropertyChanged("numeroProductoReferenciaCruzada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=43)]
        public string numeroReferencia {
            get {
                return this.numeroReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroReferenciaField, value) != true)) {
                    this.numeroReferenciaField = value;
                    this.RaisePropertyChanged("numeroReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=44)]
        public string numeroSolicitud {
            get {
                return this.numeroSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroSolicitudField, value) != true)) {
                    this.numeroSolicitudField = value;
                    this.RaisePropertyChanged("numeroSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=45)]
        public string numeroTarjetaAsignado {
            get {
                return this.numeroTarjetaAsignadoField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroTarjetaAsignadoField, value) != true)) {
                    this.numeroTarjetaAsignadoField = value;
                    this.RaisePropertyChanged("numeroTarjetaAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=46)]
        public string oficinaRadicacionSolicitud {
            get {
                return this.oficinaRadicacionSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.oficinaRadicacionSolicitudField, value) != true)) {
                    this.oficinaRadicacionSolicitudField = value;
                    this.RaisePropertyChanged("oficinaRadicacionSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=47)]
        public string origenIngresos {
            get {
                return this.origenIngresosField;
            }
            set {
                if ((object.ReferenceEquals(this.origenIngresosField, value) != true)) {
                    this.origenIngresosField = value;
                    this.RaisePropertyChanged("origenIngresos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=48)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=49)]
        public string primerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.primerNombreField, value) != true)) {
                    this.primerNombreField = value;
                    this.RaisePropertyChanged("primerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=50)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=51)]
        public string segundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoNombreField, value) != true)) {
                    this.segundoNombreField = value;
                    this.RaisePropertyChanged("segundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=52)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=53)]
        public string subtipo {
            get {
                return this.subtipoField;
            }
            set {
                if ((object.ReferenceEquals(this.subtipoField, value) != true)) {
                    this.subtipoField = value;
                    this.RaisePropertyChanged("subtipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=54)]
        public string tarjetaAnterior {
            get {
                return this.tarjetaAnteriorField;
            }
            set {
                if ((object.ReferenceEquals(this.tarjetaAnteriorField, value) != true)) {
                    this.tarjetaAnteriorField = value;
                    this.RaisePropertyChanged("tarjetaAnterior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=55)]
        public string telefonoOficina {
            get {
                return this.telefonoOficinaField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoOficinaField, value) != true)) {
                    this.telefonoOficinaField = value;
                    this.RaisePropertyChanged("telefonoOficina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=56)]
        public string telefonoResidencia {
            get {
                return this.telefonoResidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoResidenciaField, value) != true)) {
                    this.telefonoResidenciaField = value;
                    this.RaisePropertyChanged("telefonoResidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=57)]
        public string tipoCuenta {
            get {
                return this.tipoCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoCuentaField, value) != true)) {
                    this.tipoCuentaField = value;
                    this.RaisePropertyChanged("tipoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=58)]
        public string tipoCuentaDebitoAutomatico {
            get {
                return this.tipoCuentaDebitoAutomaticoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoCuentaDebitoAutomaticoField, value) != true)) {
                    this.tipoCuentaDebitoAutomaticoField = value;
                    this.RaisePropertyChanged("tipoCuentaDebitoAutomatico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=59)]
        public string tipoIdAmparador {
            get {
                return this.tipoIdAmparadorField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoIdAmparadorField, value) != true)) {
                    this.tipoIdAmparadorField = value;
                    this.RaisePropertyChanged("tipoIdAmparador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=60)]
        public string tipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoIdentificacionField, value) != true)) {
                    this.tipoIdentificacionField = value;
                    this.RaisePropertyChanged("tipoIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=61)]
        public string tipoNovedad {
            get {
                return this.tipoNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoNovedadField, value) != true)) {
                    this.tipoNovedadField = value;
                    this.RaisePropertyChanged("tipoNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=62)]
        public string tipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoPersonaField, value) != true)) {
                    this.tipoPersonaField = value;
                    this.RaisePropertyChanged("tipoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=63)]
        public string tipoSolicitud {
            get {
                return this.tipoSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoSolicitudField, value) != true)) {
                    this.tipoSolicitudField = value;
                    this.RaisePropertyChanged("tipoSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=64)]
        public string tipoTarjeta {
            get {
                return this.tipoTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoTarjetaField, value) != true)) {
                    this.tipoTarjetaField = value;
                    this.RaisePropertyChanged("tipoTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=65)]
        public string valorCuotaFija {
            get {
                return this.valorCuotaFijaField;
            }
            set {
                if ((object.ReferenceEquals(this.valorCuotaFijaField, value) != true)) {
                    this.valorCuotaFijaField = value;
                    this.RaisePropertyChanged("valorCuotaFija");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=66)]
        public string zonaPostalDireccionCorrespondencia {
            get {
                return this.zonaPostalDireccionCorrespondenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.zonaPostalDireccionCorrespondenciaField, value) != true)) {
                    this.zonaPostalDireccionCorrespondenciaField = value;
                    this.RaisePropertyChanged("zonaPostalDireccionCorrespondencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=67)]
        public string zonaPostalDireccionResidencial {
            get {
                return this.zonaPostalDireccionResidencialField;
            }
            set {
                if ((object.ReferenceEquals(this.zonaPostalDireccionResidencialField, value) != true)) {
                    this.zonaPostalDireccionResidencialField = value;
                    this.RaisePropertyChanged("zonaPostalDireccionResidencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsdl.rbm.com", ConfigurationName="NovedadesBloqueoSR.NovedadesNoMon_WS")]
    public interface NovedadesNoMon_WS {
        
        // CODEGEN: Generating message contract since element name noMon_Dto from namespace http://wsdl.rbm.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        BancaServices.NovedadesBloqueoSR.aplicarNovedadResponse aplicarNovedad(BancaServices.NovedadesBloqueoSR.aplicarNovedadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.NovedadesBloqueoSR.aplicarNovedadResponse> aplicarNovedadAsync(BancaServices.NovedadesBloqueoSR.aplicarNovedadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aplicarNovedadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aplicarNovedad", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.NovedadesBloqueoSR.aplicarNovedadRequestBody Body;
        
        public aplicarNovedadRequest() {
        }
        
        public aplicarNovedadRequest(BancaServices.NovedadesBloqueoSR.aplicarNovedadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class aplicarNovedadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.NovedadesBloqueoSR.NovedadNoMon_Dto noMon_Dto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string usrId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string usrPsw;
        
        public aplicarNovedadRequestBody() {
        }
        
        public aplicarNovedadRequestBody(BancaServices.NovedadesBloqueoSR.NovedadNoMon_Dto noMon_Dto, string usrId, string usrPsw) {
            this.noMon_Dto = noMon_Dto;
            this.usrId = usrId;
            this.usrPsw = usrPsw;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aplicarNovedadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aplicarNovedadResponse", Namespace="http://wsdl.rbm.com", Order=0)]
        public BancaServices.NovedadesBloqueoSR.aplicarNovedadResponseBody Body;
        
        public aplicarNovedadResponse() {
        }
        
        public aplicarNovedadResponse(BancaServices.NovedadesBloqueoSR.aplicarNovedadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsdl.rbm.com")]
    public partial class aplicarNovedadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.NovedadesBloqueoSR.NovedadNoMon_Dto aplicarNovedadReturn;
        
        public aplicarNovedadResponseBody() {
        }
        
        public aplicarNovedadResponseBody(BancaServices.NovedadesBloqueoSR.NovedadNoMon_Dto aplicarNovedadReturn) {
            this.aplicarNovedadReturn = aplicarNovedadReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NovedadesNoMon_WSChannel : BancaServices.NovedadesBloqueoSR.NovedadesNoMon_WS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NovedadesNoMon_WSClient : System.ServiceModel.ClientBase<BancaServices.NovedadesBloqueoSR.NovedadesNoMon_WS>, BancaServices.NovedadesBloqueoSR.NovedadesNoMon_WS {
        
        public NovedadesNoMon_WSClient() {
        }
        
        public NovedadesNoMon_WSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NovedadesNoMon_WSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NovedadesNoMon_WSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NovedadesNoMon_WSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.NovedadesBloqueoSR.aplicarNovedadResponse BancaServices.NovedadesBloqueoSR.NovedadesNoMon_WS.aplicarNovedad(BancaServices.NovedadesBloqueoSR.aplicarNovedadRequest request) {
            return base.Channel.aplicarNovedad(request);
        }
        
        public BancaServices.NovedadesBloqueoSR.NovedadNoMon_Dto aplicarNovedad(BancaServices.NovedadesBloqueoSR.NovedadNoMon_Dto noMon_Dto, string usrId, string usrPsw) {
            BancaServices.NovedadesBloqueoSR.aplicarNovedadRequest inValue = new BancaServices.NovedadesBloqueoSR.aplicarNovedadRequest();
            inValue.Body = new BancaServices.NovedadesBloqueoSR.aplicarNovedadRequestBody();
            inValue.Body.noMon_Dto = noMon_Dto;
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            BancaServices.NovedadesBloqueoSR.aplicarNovedadResponse retVal = ((BancaServices.NovedadesBloqueoSR.NovedadesNoMon_WS)(this)).aplicarNovedad(inValue);
            return retVal.Body.aplicarNovedadReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.NovedadesBloqueoSR.aplicarNovedadResponse> BancaServices.NovedadesBloqueoSR.NovedadesNoMon_WS.aplicarNovedadAsync(BancaServices.NovedadesBloqueoSR.aplicarNovedadRequest request) {
            return base.Channel.aplicarNovedadAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.NovedadesBloqueoSR.aplicarNovedadResponse> aplicarNovedadAsync(BancaServices.NovedadesBloqueoSR.NovedadNoMon_Dto noMon_Dto, string usrId, string usrPsw) {
            BancaServices.NovedadesBloqueoSR.aplicarNovedadRequest inValue = new BancaServices.NovedadesBloqueoSR.aplicarNovedadRequest();
            inValue.Body = new BancaServices.NovedadesBloqueoSR.aplicarNovedadRequestBody();
            inValue.Body.noMon_Dto = noMon_Dto;
            inValue.Body.usrId = usrId;
            inValue.Body.usrPsw = usrPsw;
            return ((BancaServices.NovedadesBloqueoSR.NovedadesNoMon_WS)(this)).aplicarNovedadAsync(inValue);
        }
    }
}
