//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaServices.PagoTcoAsNet {
    using System.Runtime.Serialization;
    
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestPagoTarjetaCreditoDTO", Namespace="http://dto.services.ws.asnetla.com")]
    [System.SerializableAttribute()]
    public partial class RequestPagoTarjetaCreditoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string fechaNovedadField;
        
        private string horaNovedadField;
        
        private string numeroIdentificacionField;
        
        private string numeroTarjetaField;
        
        private string tipoProductoField;
        
        private string valorPagoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fechaNovedad {
            get {
                return this.fechaNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaNovedadField, value) != true)) {
                    this.fechaNovedadField = value;
                    this.RaisePropertyChanged("fechaNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string horaNovedad {
            get {
                return this.horaNovedadField;
            }
            set {
                if ((object.ReferenceEquals(this.horaNovedadField, value) != true)) {
                    this.horaNovedadField = value;
                    this.RaisePropertyChanged("horaNovedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroIdentificacion {
            get {
                return this.numeroIdentificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroIdentificacionField, value) != true)) {
                    this.numeroIdentificacionField = value;
                    this.RaisePropertyChanged("numeroIdentificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroTarjeta {
            get {
                return this.numeroTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroTarjetaField, value) != true)) {
                    this.numeroTarjetaField = value;
                    this.RaisePropertyChanged("numeroTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string tipoProducto {
            get {
                return this.tipoProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoProductoField, value) != true)) {
                    this.tipoProductoField = value;
                    this.RaisePropertyChanged("tipoProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string valorPago {
            get {
                return this.valorPagoField;
            }
            set {
                if ((object.ReferenceEquals(this.valorPagoField, value) != true)) {
                    this.valorPagoField = value;
                    this.RaisePropertyChanged("valorPago");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponsePagoTarjetaCreditoDTO", Namespace="http://dto.services.ws.asnetla.com")]
    [System.SerializableAttribute()]
    public partial class ResponsePagoTarjetaCreditoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private string fechaAutorizacionField;
        
        private string horaAutorizacionField;
        
        private string numeroAutorizacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoRespuestaField, value) != true)) {
                    this.codigoRespuestaField = value;
                    this.RaisePropertyChanged("codigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionRespuestaField, value) != true)) {
                    this.descripcionRespuestaField = value;
                    this.RaisePropertyChanged("descripcionRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string fechaAutorizacion {
            get {
                return this.fechaAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaAutorizacionField, value) != true)) {
                    this.fechaAutorizacionField = value;
                    this.RaisePropertyChanged("fechaAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string horaAutorizacion {
            get {
                return this.horaAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.horaAutorizacionField, value) != true)) {
                    this.horaAutorizacionField = value;
                    this.RaisePropertyChanged("horaAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string numeroAutorizacion {
            get {
                return this.numeroAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.numeroAutorizacionField, value) != true)) {
                    this.numeroAutorizacionField = value;
                    this.RaisePropertyChanged("numeroAutorizacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.ws.asnetla.com", ConfigurationName="PagoTcoAsNet.PagoTarjetaCreditoImplService")]
    public interface PagoTarjetaCreditoImplService {
        
        // CODEGEN: Generating message contract since element name request_p from namespace http://services.ws.asnetla.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoResponse getPagoTarjetaCredito(BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoResponse> getPagoTarjetaCreditoAsync(BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPagoTarjetaCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPagoTarjetaCredito", Namespace="http://services.ws.asnetla.com", Order=0)]
        public BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequestBody Body;
        
        public getPagoTarjetaCreditoRequest() {
        }
        
        public getPagoTarjetaCreditoRequest(BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ws.asnetla.com")]
    public partial class getPagoTarjetaCreditoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.PagoTcoAsNet.RequestPagoTarjetaCreditoDTO request_p;
        
        public getPagoTarjetaCreditoRequestBody() {
        }
        
        public getPagoTarjetaCreditoRequestBody(BancaServices.PagoTcoAsNet.RequestPagoTarjetaCreditoDTO request_p) {
            this.request_p = request_p;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPagoTarjetaCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPagoTarjetaCreditoResponse", Namespace="http://services.ws.asnetla.com", Order=0)]
        public BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoResponseBody Body;
        
        public getPagoTarjetaCreditoResponse() {
        }
        
        public getPagoTarjetaCreditoResponse(BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.ws.asnetla.com")]
    public partial class getPagoTarjetaCreditoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.PagoTcoAsNet.ResponsePagoTarjetaCreditoDTO getPagoTarjetaCreditoReturn;
        
        public getPagoTarjetaCreditoResponseBody() {
        }
        
        public getPagoTarjetaCreditoResponseBody(BancaServices.PagoTcoAsNet.ResponsePagoTarjetaCreditoDTO getPagoTarjetaCreditoReturn) {
            this.getPagoTarjetaCreditoReturn = getPagoTarjetaCreditoReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PagoTarjetaCreditoImplServiceChannel : BancaServices.PagoTcoAsNet.PagoTarjetaCreditoImplService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PagoTarjetaCreditoImplServiceClient : System.ServiceModel.ClientBase<BancaServices.PagoTcoAsNet.PagoTarjetaCreditoImplService>, BancaServices.PagoTcoAsNet.PagoTarjetaCreditoImplService {
        
        public PagoTarjetaCreditoImplServiceClient() {
        }
        
        public PagoTarjetaCreditoImplServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PagoTarjetaCreditoImplServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoTarjetaCreditoImplServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PagoTarjetaCreditoImplServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoResponse BancaServices.PagoTcoAsNet.PagoTarjetaCreditoImplService.getPagoTarjetaCredito(BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequest request) {
            return base.Channel.getPagoTarjetaCredito(request);
        }
        
        public BancaServices.PagoTcoAsNet.ResponsePagoTarjetaCreditoDTO getPagoTarjetaCredito(BancaServices.PagoTcoAsNet.RequestPagoTarjetaCreditoDTO request_p) {
            BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequest inValue = new BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequest();
            inValue.Body = new BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequestBody();
            inValue.Body.request_p = request_p;
            BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoResponse retVal = ((BancaServices.PagoTcoAsNet.PagoTarjetaCreditoImplService)(this)).getPagoTarjetaCredito(inValue);
            return retVal.Body.getPagoTarjetaCreditoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoResponse> BancaServices.PagoTcoAsNet.PagoTarjetaCreditoImplService.getPagoTarjetaCreditoAsync(BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequest request) {
            return base.Channel.getPagoTarjetaCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoResponse> getPagoTarjetaCreditoAsync(BancaServices.PagoTcoAsNet.RequestPagoTarjetaCreditoDTO request_p) {
            BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequest inValue = new BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequest();
            inValue.Body = new BancaServices.PagoTcoAsNet.getPagoTarjetaCreditoRequestBody();
            inValue.Body.request_p = request_p;
            return ((BancaServices.PagoTcoAsNet.PagoTarjetaCreditoImplService)(this)).getPagoTarjetaCreditoAsync(inValue);
        }
    }
}
