//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancaServices.CERPServiceRef {
    using System.Runtime.Serialization;
    
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class InputData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string encab_mensajeria_ATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tipo_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CanalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_aplicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usuario_loguiadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_hoyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JornadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hora_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string terminal_nroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_identificacion_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ultimo_encargo_recibidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string encab_mensajeria_ATH {
            get {
                return this.encab_mensajeria_ATHField;
            }
            set {
                if ((object.ReferenceEquals(this.encab_mensajeria_ATHField, value) != true)) {
                    this.encab_mensajeria_ATHField = value;
                    this.RaisePropertyChanged("encab_mensajeria_ATH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Tipo_Registro {
            get {
                return this.Tipo_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Tipo_RegistroField, value) != true)) {
                    this.Tipo_RegistroField = value;
                    this.RaisePropertyChanged("Tipo_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Canal {
            get {
                return this.CanalField;
            }
            set {
                if ((object.ReferenceEquals(this.CanalField, value) != true)) {
                    this.CanalField = value;
                    this.RaisePropertyChanged("Canal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Cod_aplica {
            get {
                return this.Cod_aplicaField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_aplicaField, value) != true)) {
                    this.Cod_aplicaField = value;
                    this.RaisePropertyChanged("Cod_aplica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Usuario_loguiado {
            get {
                return this.Usuario_loguiadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Usuario_loguiadoField, value) != true)) {
                    this.Usuario_loguiadoField = value;
                    this.RaisePropertyChanged("Usuario_loguiado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Fecha_hoy {
            get {
                return this.Fecha_hoyField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_hoyField, value) != true)) {
                    this.Fecha_hoyField = value;
                    this.RaisePropertyChanged("Fecha_hoy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Jornada {
            get {
                return this.JornadaField;
            }
            set {
                if ((object.ReferenceEquals(this.JornadaField, value) != true)) {
                    this.JornadaField = value;
                    this.RaisePropertyChanged("Jornada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string hora_inicio {
            get {
                return this.hora_inicioField;
            }
            set {
                if ((object.ReferenceEquals(this.hora_inicioField, value) != true)) {
                    this.hora_inicioField = value;
                    this.RaisePropertyChanged("hora_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string terminal_nro {
            get {
                return this.terminal_nroField;
            }
            set {
                if ((object.ReferenceEquals(this.terminal_nroField, value) != true)) {
                    this.terminal_nroField = value;
                    this.RaisePropertyChanged("terminal_nro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string nro_identificacion_cliente {
            get {
                return this.nro_identificacion_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_identificacion_clienteField, value) != true)) {
                    this.nro_identificacion_clienteField = value;
                    this.RaisePropertyChanged("nro_identificacion_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Ultimo_encargo_recibido {
            get {
                return this.Ultimo_encargo_recibidoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ultimo_encargo_recibidoField, value) != true)) {
                    this.Ultimo_encargo_recibidoField = value;
                    this.RaisePropertyChanged("Ultimo_encargo_recibido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OutputData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string encab_mensajeria_ATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_registroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_validacion_fiduoccidenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_validacion_infField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_ocurrenciasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Codigo_fondo_inversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_ofic_const_encargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_encargo_fiduciarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecha_ultimo_cierre_fondoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Saldo_disponible_en_pesos_encargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cod_ent_bancaria_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_cuenta_bancaria_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vlr_unidad_fondoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Saldo_en_unidades_del_fideicomisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Saldo_total_en_pesos_encargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nicknameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string encab_mensajeria_ATH {
            get {
                return this.encab_mensajeria_ATHField;
            }
            set {
                if ((object.ReferenceEquals(this.encab_mensajeria_ATHField, value) != true)) {
                    this.encab_mensajeria_ATHField = value;
                    this.RaisePropertyChanged("encab_mensajeria_ATH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tipo_registro {
            get {
                return this.tipo_registroField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_registroField, value) != true)) {
                    this.tipo_registroField = value;
                    this.RaisePropertyChanged("tipo_registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cod_validacion_fiduoccidente {
            get {
                return this.cod_validacion_fiduoccidenteField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_validacion_fiduoccidenteField, value) != true)) {
                    this.cod_validacion_fiduoccidenteField = value;
                    this.RaisePropertyChanged("cod_validacion_fiduoccidente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cod_validacion_inf {
            get {
                return this.cod_validacion_infField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_validacion_infField, value) != true)) {
                    this.cod_validacion_infField = value;
                    this.RaisePropertyChanged("cod_validacion_inf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nombre_cliente {
            get {
                return this.nombre_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_clienteField, value) != true)) {
                    this.nombre_clienteField = value;
                    this.RaisePropertyChanged("nombre_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nro_ocurrencias {
            get {
                return this.nro_ocurrenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_ocurrenciasField, value) != true)) {
                    this.nro_ocurrenciasField = value;
                    this.RaisePropertyChanged("nro_ocurrencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Codigo_fondo_inversion {
            get {
                return this.Codigo_fondo_inversionField;
            }
            set {
                if ((object.ReferenceEquals(this.Codigo_fondo_inversionField, value) != true)) {
                    this.Codigo_fondo_inversionField = value;
                    this.RaisePropertyChanged("Codigo_fondo_inversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cod_ofic_const_encargo {
            get {
                return this.cod_ofic_const_encargoField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_ofic_const_encargoField, value) != true)) {
                    this.cod_ofic_const_encargoField = value;
                    this.RaisePropertyChanged("cod_ofic_const_encargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string nro_encargo_fiduciario {
            get {
                return this.nro_encargo_fiduciarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_encargo_fiduciarioField, value) != true)) {
                    this.nro_encargo_fiduciarioField = value;
                    this.RaisePropertyChanged("nro_encargo_fiduciario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string fecha_ultimo_cierre_fondo {
            get {
                return this.fecha_ultimo_cierre_fondoField;
            }
            set {
                if ((object.ReferenceEquals(this.fecha_ultimo_cierre_fondoField, value) != true)) {
                    this.fecha_ultimo_cierre_fondoField = value;
                    this.RaisePropertyChanged("fecha_ultimo_cierre_fondo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Saldo_disponible_en_pesos_encargo {
            get {
                return this.Saldo_disponible_en_pesos_encargoField;
            }
            set {
                if ((object.ReferenceEquals(this.Saldo_disponible_en_pesos_encargoField, value) != true)) {
                    this.Saldo_disponible_en_pesos_encargoField = value;
                    this.RaisePropertyChanged("Saldo_disponible_en_pesos_encargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string cod_ent_bancaria_cliente {
            get {
                return this.cod_ent_bancaria_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.cod_ent_bancaria_clienteField, value) != true)) {
                    this.cod_ent_bancaria_clienteField = value;
                    this.RaisePropertyChanged("cod_ent_bancaria_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string nro_cuenta_bancaria_cliente {
            get {
                return this.nro_cuenta_bancaria_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_cuenta_bancaria_clienteField, value) != true)) {
                    this.nro_cuenta_bancaria_clienteField = value;
                    this.RaisePropertyChanged("nro_cuenta_bancaria_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string vlr_unidad_fondo {
            get {
                return this.vlr_unidad_fondoField;
            }
            set {
                if ((object.ReferenceEquals(this.vlr_unidad_fondoField, value) != true)) {
                    this.vlr_unidad_fondoField = value;
                    this.RaisePropertyChanged("vlr_unidad_fondo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Saldo_en_unidades_del_fideicomiso {
            get {
                return this.Saldo_en_unidades_del_fideicomisoField;
            }
            set {
                if ((object.ReferenceEquals(this.Saldo_en_unidades_del_fideicomisoField, value) != true)) {
                    this.Saldo_en_unidades_del_fideicomisoField = value;
                    this.RaisePropertyChanged("Saldo_en_unidades_del_fideicomiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string Saldo_total_en_pesos_encargo {
            get {
                return this.Saldo_total_en_pesos_encargoField;
            }
            set {
                if ((object.ReferenceEquals(this.Saldo_total_en_pesos_encargoField, value) != true)) {
                    this.Saldo_total_en_pesos_encargoField = value;
                    this.RaisePropertyChanged("Saldo_total_en_pesos_encargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CERPServiceRef.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessDataStruct", ReplyAction="*")]
        BancaServices.CERPServiceRef.ProcessDataStructResponse ProcessDataStruct(BancaServices.CERPServiceRef.ProcessDataStructRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessDataStruct", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataStructResponse> ProcessDataStructAsync(BancaServices.CERPServiceRef.ProcessDataStructRequest request);
        
        // CODEGEN: Generating message contract since element name GetInputXmlFormatResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInputXmlFormat", ReplyAction="*")]
        BancaServices.CERPServiceRef.GetInputXmlFormatResponse GetInputXmlFormat(BancaServices.CERPServiceRef.GetInputXmlFormatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInputXmlFormat", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.GetInputXmlFormatResponse> GetInputXmlFormatAsync(BancaServices.CERPServiceRef.GetInputXmlFormatRequest request);
        
        // CODEGEN: Generating message contract since element name GetOutputXmlFormatResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOutputXmlFormat", ReplyAction="*")]
        BancaServices.CERPServiceRef.GetOutputXmlFormatResponse GetOutputXmlFormat(BancaServices.CERPServiceRef.GetOutputXmlFormatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOutputXmlFormat", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.GetOutputXmlFormatResponse> GetOutputXmlFormatAsync(BancaServices.CERPServiceRef.GetOutputXmlFormatRequest request);
        
        // CODEGEN: Generating message contract since element name s from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessData", ReplyAction="*")]
        BancaServices.CERPServiceRef.ProcessDataResponse ProcessData(BancaServices.CERPServiceRef.ProcessDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessData", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataResponse> ProcessDataAsync(BancaServices.CERPServiceRef.ProcessDataRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessDataStruct2", ReplyAction="*")]
        BancaServices.CERPServiceRef.ProcessDataStruct2Response ProcessDataStruct2(BancaServices.CERPServiceRef.ProcessDataStruct2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessDataStruct2", ReplyAction="*")]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataStruct2Response> ProcessDataStruct2Async(BancaServices.CERPServiceRef.ProcessDataStruct2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDataStructRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessDataStruct", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.ProcessDataStructRequestBody Body;
        
        public ProcessDataStructRequest() {
        }
        
        public ProcessDataStructRequest(BancaServices.CERPServiceRef.ProcessDataStructRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessDataStructRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.CERPServiceRef.InputData data;
        
        public ProcessDataStructRequestBody() {
        }
        
        public ProcessDataStructRequestBody(BancaServices.CERPServiceRef.InputData data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDataStructResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessDataStructResponse", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.ProcessDataStructResponseBody Body;
        
        public ProcessDataStructResponse() {
        }
        
        public ProcessDataStructResponse(BancaServices.CERPServiceRef.ProcessDataStructResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessDataStructResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.CERPServiceRef.OutputData ProcessDataStructResult;
        
        public ProcessDataStructResponseBody() {
        }
        
        public ProcessDataStructResponseBody(BancaServices.CERPServiceRef.OutputData ProcessDataStructResult) {
            this.ProcessDataStructResult = ProcessDataStructResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInputXmlFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInputXmlFormat", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.GetInputXmlFormatRequestBody Body;
        
        public GetInputXmlFormatRequest() {
        }
        
        public GetInputXmlFormatRequest(BancaServices.CERPServiceRef.GetInputXmlFormatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInputXmlFormatRequestBody {
        
        public GetInputXmlFormatRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInputXmlFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInputXmlFormatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.GetInputXmlFormatResponseBody Body;
        
        public GetInputXmlFormatResponse() {
        }
        
        public GetInputXmlFormatResponse(BancaServices.CERPServiceRef.GetInputXmlFormatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInputXmlFormatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInputXmlFormatResult;
        
        public GetInputXmlFormatResponseBody() {
        }
        
        public GetInputXmlFormatResponseBody(string GetInputXmlFormatResult) {
            this.GetInputXmlFormatResult = GetInputXmlFormatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOutputXmlFormatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOutputXmlFormat", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.GetOutputXmlFormatRequestBody Body;
        
        public GetOutputXmlFormatRequest() {
        }
        
        public GetOutputXmlFormatRequest(BancaServices.CERPServiceRef.GetOutputXmlFormatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetOutputXmlFormatRequestBody {
        
        public GetOutputXmlFormatRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOutputXmlFormatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOutputXmlFormatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.GetOutputXmlFormatResponseBody Body;
        
        public GetOutputXmlFormatResponse() {
        }
        
        public GetOutputXmlFormatResponse(BancaServices.CERPServiceRef.GetOutputXmlFormatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOutputXmlFormatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOutputXmlFormatResult;
        
        public GetOutputXmlFormatResponseBody() {
        }
        
        public GetOutputXmlFormatResponseBody(string GetOutputXmlFormatResult) {
            this.GetOutputXmlFormatResult = GetOutputXmlFormatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessData", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.ProcessDataRequestBody Body;
        
        public ProcessDataRequest() {
        }
        
        public ProcessDataRequest(BancaServices.CERPServiceRef.ProcessDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public ProcessDataRequestBody() {
        }
        
        public ProcessDataRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.ProcessDataResponseBody Body;
        
        public ProcessDataResponse() {
        }
        
        public ProcessDataResponse(BancaServices.CERPServiceRef.ProcessDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessDataResult;
        
        public ProcessDataResponseBody() {
        }
        
        public ProcessDataResponseBody(string ProcessDataResult) {
            this.ProcessDataResult = ProcessDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDataStruct2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessDataStruct2", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.ProcessDataStruct2RequestBody Body;
        
        public ProcessDataStruct2Request() {
        }
        
        public ProcessDataStruct2Request(BancaServices.CERPServiceRef.ProcessDataStruct2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessDataStruct2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.CERPServiceRef.InputData data;
        
        public ProcessDataStruct2RequestBody() {
        }
        
        public ProcessDataStruct2RequestBody(BancaServices.CERPServiceRef.InputData data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessDataStruct2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessDataStruct2Response", Namespace="http://tempuri.org/", Order=0)]
        public BancaServices.CERPServiceRef.ProcessDataStruct2ResponseBody Body;
        
        public ProcessDataStruct2Response() {
        }
        
        public ProcessDataStruct2Response(BancaServices.CERPServiceRef.ProcessDataStruct2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessDataStruct2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BancaServices.CERPServiceRef.OutputData[] ProcessDataStruct2Result;
        
        public ProcessDataStruct2ResponseBody() {
        }
        
        public ProcessDataStruct2ResponseBody(BancaServices.CERPServiceRef.OutputData[] ProcessDataStruct2Result) {
            this.ProcessDataStruct2Result = ProcessDataStruct2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BancaServices.CERPServiceRef.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BancaServices.CERPServiceRef.ServiceSoap>, BancaServices.CERPServiceRef.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.CERPServiceRef.ProcessDataStructResponse BancaServices.CERPServiceRef.ServiceSoap.ProcessDataStruct(BancaServices.CERPServiceRef.ProcessDataStructRequest request) {
            return base.Channel.ProcessDataStruct(request);
        }
        
        public BancaServices.CERPServiceRef.OutputData ProcessDataStruct(BancaServices.CERPServiceRef.InputData data) {
            BancaServices.CERPServiceRef.ProcessDataStructRequest inValue = new BancaServices.CERPServiceRef.ProcessDataStructRequest();
            inValue.Body = new BancaServices.CERPServiceRef.ProcessDataStructRequestBody();
            inValue.Body.data = data;
            BancaServices.CERPServiceRef.ProcessDataStructResponse retVal = ((BancaServices.CERPServiceRef.ServiceSoap)(this)).ProcessDataStruct(inValue);
            return retVal.Body.ProcessDataStructResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataStructResponse> BancaServices.CERPServiceRef.ServiceSoap.ProcessDataStructAsync(BancaServices.CERPServiceRef.ProcessDataStructRequest request) {
            return base.Channel.ProcessDataStructAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataStructResponse> ProcessDataStructAsync(BancaServices.CERPServiceRef.InputData data) {
            BancaServices.CERPServiceRef.ProcessDataStructRequest inValue = new BancaServices.CERPServiceRef.ProcessDataStructRequest();
            inValue.Body = new BancaServices.CERPServiceRef.ProcessDataStructRequestBody();
            inValue.Body.data = data;
            return ((BancaServices.CERPServiceRef.ServiceSoap)(this)).ProcessDataStructAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.CERPServiceRef.GetInputXmlFormatResponse BancaServices.CERPServiceRef.ServiceSoap.GetInputXmlFormat(BancaServices.CERPServiceRef.GetInputXmlFormatRequest request) {
            return base.Channel.GetInputXmlFormat(request);
        }
        
        public string GetInputXmlFormat() {
            BancaServices.CERPServiceRef.GetInputXmlFormatRequest inValue = new BancaServices.CERPServiceRef.GetInputXmlFormatRequest();
            inValue.Body = new BancaServices.CERPServiceRef.GetInputXmlFormatRequestBody();
            BancaServices.CERPServiceRef.GetInputXmlFormatResponse retVal = ((BancaServices.CERPServiceRef.ServiceSoap)(this)).GetInputXmlFormat(inValue);
            return retVal.Body.GetInputXmlFormatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.GetInputXmlFormatResponse> BancaServices.CERPServiceRef.ServiceSoap.GetInputXmlFormatAsync(BancaServices.CERPServiceRef.GetInputXmlFormatRequest request) {
            return base.Channel.GetInputXmlFormatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.CERPServiceRef.GetInputXmlFormatResponse> GetInputXmlFormatAsync() {
            BancaServices.CERPServiceRef.GetInputXmlFormatRequest inValue = new BancaServices.CERPServiceRef.GetInputXmlFormatRequest();
            inValue.Body = new BancaServices.CERPServiceRef.GetInputXmlFormatRequestBody();
            return ((BancaServices.CERPServiceRef.ServiceSoap)(this)).GetInputXmlFormatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.CERPServiceRef.GetOutputXmlFormatResponse BancaServices.CERPServiceRef.ServiceSoap.GetOutputXmlFormat(BancaServices.CERPServiceRef.GetOutputXmlFormatRequest request) {
            return base.Channel.GetOutputXmlFormat(request);
        }
        
        public string GetOutputXmlFormat() {
            BancaServices.CERPServiceRef.GetOutputXmlFormatRequest inValue = new BancaServices.CERPServiceRef.GetOutputXmlFormatRequest();
            inValue.Body = new BancaServices.CERPServiceRef.GetOutputXmlFormatRequestBody();
            BancaServices.CERPServiceRef.GetOutputXmlFormatResponse retVal = ((BancaServices.CERPServiceRef.ServiceSoap)(this)).GetOutputXmlFormat(inValue);
            return retVal.Body.GetOutputXmlFormatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.GetOutputXmlFormatResponse> BancaServices.CERPServiceRef.ServiceSoap.GetOutputXmlFormatAsync(BancaServices.CERPServiceRef.GetOutputXmlFormatRequest request) {
            return base.Channel.GetOutputXmlFormatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.CERPServiceRef.GetOutputXmlFormatResponse> GetOutputXmlFormatAsync() {
            BancaServices.CERPServiceRef.GetOutputXmlFormatRequest inValue = new BancaServices.CERPServiceRef.GetOutputXmlFormatRequest();
            inValue.Body = new BancaServices.CERPServiceRef.GetOutputXmlFormatRequestBody();
            return ((BancaServices.CERPServiceRef.ServiceSoap)(this)).GetOutputXmlFormatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.CERPServiceRef.ProcessDataResponse BancaServices.CERPServiceRef.ServiceSoap.ProcessData(BancaServices.CERPServiceRef.ProcessDataRequest request) {
            return base.Channel.ProcessData(request);
        }
        
        public string ProcessData(string s) {
            BancaServices.CERPServiceRef.ProcessDataRequest inValue = new BancaServices.CERPServiceRef.ProcessDataRequest();
            inValue.Body = new BancaServices.CERPServiceRef.ProcessDataRequestBody();
            inValue.Body.s = s;
            BancaServices.CERPServiceRef.ProcessDataResponse retVal = ((BancaServices.CERPServiceRef.ServiceSoap)(this)).ProcessData(inValue);
            return retVal.Body.ProcessDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataResponse> BancaServices.CERPServiceRef.ServiceSoap.ProcessDataAsync(BancaServices.CERPServiceRef.ProcessDataRequest request) {
            return base.Channel.ProcessDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataResponse> ProcessDataAsync(string s) {
            BancaServices.CERPServiceRef.ProcessDataRequest inValue = new BancaServices.CERPServiceRef.ProcessDataRequest();
            inValue.Body = new BancaServices.CERPServiceRef.ProcessDataRequestBody();
            inValue.Body.s = s;
            return ((BancaServices.CERPServiceRef.ServiceSoap)(this)).ProcessDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BancaServices.CERPServiceRef.ProcessDataStruct2Response BancaServices.CERPServiceRef.ServiceSoap.ProcessDataStruct2(BancaServices.CERPServiceRef.ProcessDataStruct2Request request) {
            return base.Channel.ProcessDataStruct2(request);
        }
        
        public BancaServices.CERPServiceRef.OutputData[] ProcessDataStruct2(BancaServices.CERPServiceRef.InputData data) {
            BancaServices.CERPServiceRef.ProcessDataStruct2Request inValue = new BancaServices.CERPServiceRef.ProcessDataStruct2Request();
            inValue.Body = new BancaServices.CERPServiceRef.ProcessDataStruct2RequestBody();
            inValue.Body.data = data;
            BancaServices.CERPServiceRef.ProcessDataStruct2Response retVal = ((BancaServices.CERPServiceRef.ServiceSoap)(this)).ProcessDataStruct2(inValue);
            return retVal.Body.ProcessDataStruct2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataStruct2Response> BancaServices.CERPServiceRef.ServiceSoap.ProcessDataStruct2Async(BancaServices.CERPServiceRef.ProcessDataStruct2Request request) {
            return base.Channel.ProcessDataStruct2Async(request);
        }
        
        public System.Threading.Tasks.Task<BancaServices.CERPServiceRef.ProcessDataStruct2Response> ProcessDataStruct2Async(BancaServices.CERPServiceRef.InputData data) {
            BancaServices.CERPServiceRef.ProcessDataStruct2Request inValue = new BancaServices.CERPServiceRef.ProcessDataStruct2Request();
            inValue.Body = new BancaServices.CERPServiceRef.ProcessDataStruct2RequestBody();
            inValue.Body.data = data;
            return ((BancaServices.CERPServiceRef.ServiceSoap)(this)).ProcessDataStruct2Async(inValue);
        }
    }
}
